next_year_second_player(A,B) :-
   does(A,B,C), my_true_year_second_player(A,B).
next_year_second_player(A,B) :-
   my_true_year_second_player(A,B), my_input_water_col(A,B,A).
next_year_second_player(6,blue).
next_year_second_player(8,red).
next_year_second_player(10,red).
next_year_second_player(12,red).
next_year_second_player(14,red).
next_year_second_player(16,blue).
next_year_second_player(18,blue).
next_year_second_player(19,blue).
next_year_second_player(20,blue).
next_year_second_player(22,blue).
next_year_second_player(24,red).
next_year_second_player(26,red).
next_year_second_player(28,red).
next_year_second_player(30,red).
next_year_second_player(32,blue).
next_year_second_player(34,blue).
next_year_second_player(35,blue).
next_year_second_player(36,blue).
next_year_second_player(38,blue).
next_year_second_player(40,red).
next_year_second_player(42,red).
next_year_second_player(44,red).
next_year_second_player(46,red).
next_year_second_player(48,blue).
next_year_second_player(50,blue).
next_year_second_player(52,blue).
next_year_second_player(53,blue).
next_year_second_player(54,blue).
next_year_second_player(56,red).
next_year_second_player(58,red).
next_year_second_player(60,red).
next_year_second_player(62,red).
next_year_second_player(64,blue).
next_year_second_player(66,blue).
next_year_second_player(67,blue).
next_year_second_player(68,blue).
next_year_second_player(70,blue).
next_year_second_player(72,red).
next_year_second_player(74,red).
next_year_second_player(76,red).
next_year_second_player(78,red).
next_year_second_player(80,blue).
next_year_second_player(82,blue).
next_year_second_player(84,blue).
next_year_second_player(86,blue).
next_year_second_player(88,red).
next_year_second_player(90,red).
next_year_second_player(92,red).
next_year_second_player(94,red).
next_year_second_player(96,blue).
next_year_second_player(98,blue).
next_year_second_player(99,blue).
next_year_second_player(100,blue).
next_year_second_player(102,blue).
next_year_second_player(104,red).
next_year_second_player(106,red).
next_year_second_player(108,red).
next_year_second_player(110,red).
next_year_second_player(112,blue).
next_year_second_player(114,blue).
next_year_second_player(115,blue).
next_year_second_player(116,blue).
next_year_second_player(118,blue).
next_year_second_player(120,red).
next_year_second_player(122,red).
next_year_second_player(124,red).
next_year_second_player(126,red).
next_year_second_player(128,blue).
next_year_second_player(130,blue).
next_year_second_player(131,blue).
next_year_second_player(132,blue).
next_year_second_player(134,blue).
next_year_second_player(136,red).
next_year_second_player(138,red).
next_year_second_player(140,red).
next_year_second_player(142,red).
next_year_second_player(144,blue).
next_year_second_player(146,blue).
next_year_second_player(147,blue).
next_year_second_player(148,blue).
next_year_second_player(150,blue).
next_year_second_player(152,red).
next_year_second_player(154,red).
next_year_second_player(156,red).
next_year_second_player(158,red).
next_year_second_player(160,blue).
next_year_second_player(162,blue).
next_year_second_player(164,blue).
next_year_second_player(166,blue).
next_year_second_player(168,red).
next_year_second_player(170,red).
next_year_second_player(172,red).
next_year_second_player(174,red).
next_year_second_player(176,blue).
next_year_second_player(178,blue).
next_year_second_player(180,blue).
next_year_second_player(181,blue).
next_year_second_player(182,blue).
next_year_second_player(184,red).
next_year_second_player(186,red).
next_year_second_player(188,red).
next_year_second_player(190,red).
next_year_second_player(192,blue).
next_year_second_player(194,blue).
next_year_second_player(195,blue).
next_year_second_player(196,blue).
next_year_second_player(198,blue).
next_year_second_player(200,red).
next_year_second_player(202,red).
next_year_second_player(204,red).
next_year_second_player(206,red).
next_year_second_player(208,blue).
next_year_second_player(210,blue).
next_year_second_player(211,blue).
next_year_second_player(212,blue).
next_year_second_player(214,blue).
next_year_second_player(216,red).
next_year_second_player(218,red).
next_year_second_player(220,red).
next_year_second_player(222,red).
next_year_second_player(224,blue).
next_year_second_player(226,blue).
next_year_second_player(228,blue).
next_year_second_player(229,blue).
next_year_second_player(230,blue).
next_year_second_player(232,red).
next_year_second_player(234,red).
next_year_second_player(236,red).
next_year_second_player(238,red).
next_year_second_player(240,blue).
next_year_second_player(242,blue).
next_year_second_player(244,blue).
next_year_second_player(246,blue).
next_year_second_player(248,red).
next_year_second_player(250,red).
next_year_second_player(252,red).
next_year_second_player(254,red).
next_year_second_player(256,blue).
next_year_second_player(258,blue).
next_year_second_player(259,blue).
next_year_second_player(260,blue).
next_year_second_player(262,blue).
next_year_second_player(264,red).
next_year_second_player(266,red).
next_year_second_player(268,red).
next_year_second_player(270,red).
next_year_second_player(272,blue).
next_year_second_player(274,blue).
next_year_second_player(275,blue).
next_year_second_player(276,blue).
next_year_second_player(278,blue).
next_year_second_player(280,red).
next_year_second_player(282,red).
next_year_second_player(284,red).
next_year_second_player(286,red).
next_year_second_player(288,blue).
next_year_second_player(290,blue).
next_year_second_player(291,blue).
next_year_second_player(292,blue).
next_year_second_player(294,blue).
next_year_second_player(296,red).
next_year_second_player(298,red).
next_year_second_player(300,red).
next_year_second_player(302,red).
next_year_second_player(304,blue).
next_year_second_player(306,blue).
next_year_second_player(307,blue).
next_year_second_player(308,blue).
next_year_second_player(310,blue).
next_year_second_player(312,red).
next_year_second_player(314,red).
next_year_second_player(316,red).
next_year_second_player(318,red).
next_year_second_player(320,blue).
next_year_second_player(322,blue).
next_year_second_player(324,blue).
next_year_second_player(326,blue).
next_year_second_player(328,red).
next_year_second_player(330,red).
next_year_second_player(332,red).
next_year_second_player(334,red).
next_year_second_player(336,blue).
next_year_second_player(338,blue).
next_year_second_player(339,blue).
next_year_second_player(340,blue).
next_year_second_player(342,blue).
next_year_second_player(344,red).
next_year_second_player(346,red).
next_year_second_player(348,red).
next_year_second_player(350,red).
next_year_second_player(352,blue).
next_year_second_player(354,blue).
next_year_second_player(356,blue).
next_year_second_player(357,blue).
next_year_second_player(358,blue).
next_year_second_player(360,red).
next_year_second_player(362,red).
next_year_second_player(364,red).
next_year_second_player(366,red).
next_year_second_player(368,blue).
next_year_second_player(370,blue).
next_year_second_player(371,blue).
next_year_second_player(372,blue).
next_year_second_player(374,blue).
next_year_second_player(376,red).
next_year_second_player(378,red).
next_year_second_player(380,red).
next_year_second_player(382,red).
next_year_second_player(384,blue).
next_year_second_player(386,blue).
next_year_second_player(387,blue).
next_year_second_player(388,blue).
next_year_second_player(390,blue).
next_year_second_player(392,red).
next_year_second_player(394,red).
next_year_second_player(396,red).
next_year_second_player(398,red).
next_year_second_player(400,blue).
next_year_second_player(402,blue).
next_year_second_player(404,blue).
next_year_second_player(406,blue).
next_year_second_player(408,red).
next_year_second_player(410,red).
next_year_second_player(412,red).
next_year_second_player(414,red).
next_year_second_player(416,blue).
next_year_second_player(418,blue).
next_year_second_player(419,blue).
next_year_second_player(420,blue).
next_year_second_player(422,blue).
next_year_second_player(424,red).
next_year_second_player(426,red).
next_year_second_player(428,red).
next_year_second_player(430,red).
next_year_second_player(432,blue).
next_year_second_player(434,blue).
next_year_second_player(435,blue).
next_year_second_player(436,blue).
next_year_second_player(438,blue).
next_year_second_player(440,red).
next_year_second_player(442,red).
next_year_second_player(444,red).
next_year_second_player(446,red).
next_year_second_player(448,blue).
next_year_second_player(450,blue).
next_year_second_player(451,blue).
next_year_second_player(452,blue).
next_year_second_player(454,blue).
next_year_second_player(456,red).
next_year_second_player(458,red).
next_year_second_player(460,red).
next_year_second_player(462,red).
next_year_second_player(464,blue).
next_year_second_player(466,blue).
next_year_second_player(467,blue).
next_year_second_player(468,blue).
next_year_second_player(470,blue).
next_year_second_player(472,red).
next_year_second_player(474,red).
next_year_second_player(476,red).
next_year_second_player(478,red).
next_year_second_player(480,blue).
next_year_second_player(482,blue).
next_year_second_player(484,blue).
next_year_second_player(486,blue).
next_year_second_player(488,red).
next_year_second_player(490,red).
next_year_second_player(492,red).
next_year_second_player(494,red).
next_year_second_player(496,blue).
next_year_second_player(498,blue).
next_year_second_player(499,blue).
next_year_second_player(500,blue).
next_year_second_player(502,blue).
next_year_second_player(504,red).
next_year_second_player(506,red).
next_year_second_player(508,red).
next_year_second_player(510,red).
next_year_second_player(512,blue).
next_year_second_player(514,blue).
next_year_second_player(515,blue).
next_year_second_player(516,blue).
next_year_second_player(518,blue).
next_year_second_player(520,red).
next_year_second_player(522,red).
next_year_second_player(524,red).
next_year_second_player(526,red).
next_year_second_player(528,blue).
next_year_second_player(530,blue).
next_year_second_player(531,blue).
next_year_second_player(532,blue).
next_year_second_player(534,blue).
next_year_second_player(536,red).
next_year_second_player(538,red).
next_year_second_player(540,red).
next_year_second_player(542,red).
next_year_second_player(544,blue).
next_year_second_player(546,blue).
next_year_second_player(547,blue).
next_year_second_player(548,blue).
next_year_second_player(550,blue).
next_year_second_player(552,red).
next_year_second_player(554,red).
next_year_second_player(556,red).
next_year_second_player(558,red).
next_year_second_player(560,blue).
next_year_second_player(562,blue).
next_year_second_player(564,blue).
next_year_second_player(566,blue).
next_year_second_player(568,red).
next_year_second_player(570,red).
next_year_second_player(572,red).
next_year_second_player(574,red).
next_year_second_player(576,blue).
next_year_second_player(578,blue).
next_year_second_player(579,blue).
next_year_second_player(580,blue).
next_year_second_player(582,blue).
next_year_second_player(584,red).
next_year_second_player(586,red).
next_year_second_player(588,red).
next_year_second_player(590,red).
next_year_second_player(592,blue).
next_year_second_player(594,blue).
next_year_second_player(595,blue).
next_year_second_player(596,blue).
next_year_second_player(598,blue).
next_year_second_player(600,red).
next_year_second_player(602,red).
next_year_second_player(604,red).
next_year_second_player(606,red).
next_year_second_player(608,blue).
next_year_second_player(610,blue).
next_year_second_player(611,blue).
next_year_second_player(612,blue).
next_year_second_player(614,blue).
next_year_second_player(616,red).
next_year_second_player(618,red).
next_year_second_player(620,red).
next_year_second_player(622,red).
next_year_second_player(624,blue).
next_year_second_player(626,blue).
next_year_second_player(627,blue).
next_year_second_player(628,blue).
next_year_second_player(630,blue).
next_year_second_player(632,red).
next_year_second_player(634,red).
next_year_second_player(636,red).
next_year_second_player(638,red).
next_year_second_player(640,blue).
next_year_second_player(642,blue).
next_year_second_player(644,blue).
next_year_second_player(646,blue).
next_year_second_player(648,red).
next_year_second_player(650,red).
next_year_second_player(652,red).
next_year_second_player(654,red).
next_year_second_player(656,blue).
next_year_second_player(658,blue).
next_year_second_player(659,blue).
next_year_second_player(660,blue).
next_year_second_player(662,blue).
next_year_second_player(664,red).
next_year_second_player(666,red).
next_year_second_player(668,red).
next_year_second_player(670,red).
next_year_second_player(672,blue).
next_year_second_player(674,blue).
next_year_second_player(675,blue).
next_year_second_player(676,blue).
next_year_second_player(678,blue).
next_year_second_player(680,red).
next_year_second_player(682,red).
next_year_second_player(684,red).
next_year_second_player(686,red).
next_year_second_player(688,blue).
next_year_second_player(690,blue).
next_year_second_player(691,blue).
next_year_second_player(692,blue).
next_year_second_player(694,blue).
next_year_second_player(696,red).
next_year_second_player(698,red).
next_year_second_player(700,red).
next_year_second_player(702,red).
next_year_second_player(704,blue).
next_year_second_player(706,blue).
next_year_second_player(708,blue).
next_year_second_player(709,blue).
next_year_second_player(710,blue).
next_year_second_player(712,red).
next_year_second_player(714,red).
next_year_second_player(716,red).
next_year_second_player(718,red).
next_year_second_player(720,blue).
next_year_second_player(722,blue).
next_year_second_player(724,blue).
next_year_second_player(726,blue).
next_year_second_player(728,red).
next_year_second_player(730,red).
next_year_second_player(732,red).
next_year_second_player(734,red).
next_year_second_player(736,blue).
next_year_second_player(738,blue).
next_year_second_player(739,blue).
next_year_second_player(740,blue).
next_year_second_player(742,blue).
next_year_second_player(744,red).
next_year_second_player(746,red).
next_year_second_player(748,red).
next_year_second_player(750,red).
next_year_second_player(752,blue).
next_year_second_player(754,blue).
next_year_second_player(755,blue).
next_year_second_player(756,blue).
next_year_second_player(758,blue).
next_year_second_player(760,red).
next_year_second_player(762,red).
next_year_second_player(764,red).
next_year_second_player(766,red).
next_year_second_player(768,blue).
next_year_second_player(770,blue).
next_year_second_player(771,blue).
next_year_second_player(772,blue).
next_year_second_player(774,blue).
next_year_second_player(776,red).
next_year_second_player(778,red).
next_year_second_player(780,red).
next_year_second_player(782,red).
next_year_second_player(784,blue).
next_year_second_player(786,blue).
next_year_second_player(787,blue).
next_year_second_player(788,blue).
next_year_second_player(790,blue).
next_year_second_player(792,red).
next_year_second_player(794,red).
next_year_second_player(796,red).
next_year_second_player(798,red).
next_year_second_player(800,blue).
next_year_second_player(802,blue).
next_year_second_player(804,blue).
next_year_second_player(806,blue).
next_year_second_player(808,red).
next_year_second_player(810,red).
next_year_second_player(812,red).
next_year_second_player(814,red).
next_year_second_player(816,blue).
next_year_second_player(818,blue).
next_year_second_player(819,blue).
next_year_second_player(820,blue).
next_year_second_player(822,blue).
next_year_second_player(824,red).
next_year_second_player(826,red).
next_year_second_player(828,red).
next_year_second_player(830,red).
next_year_second_player(832,blue).
next_year_second_player(834,blue).
next_year_second_player(835,blue).
next_year_second_player(836,blue).
next_year_second_player(838,blue).
next_year_second_player(840,red).
next_year_second_player(842,red).
next_year_second_player(844,red).
next_year_second_player(846,red).
next_year_second_player(848,blue).
next_year_second_player(850,blue).
next_year_second_player(852,blue).
next_year_second_player(853,blue).
next_year_second_player(854,blue).
next_year_second_player(856,red).
next_year_second_player(858,red).
next_year_second_player(860,red).
next_year_second_player(862,red).
next_year_second_player(864,blue).
next_year_second_player(866,blue).
next_year_second_player(867,blue).
next_year_second_player(868,blue).
next_year_second_player(870,blue).
next_year_second_player(872,red).
next_year_second_player(874,red).
next_year_second_player(876,red).
next_year_second_player(878,red).
next_year_second_player(880,blue).
next_year_second_player(882,blue).
next_year_second_player(884,blue).
next_year_second_player(886,blue).
next_year_second_player(888,red).
next_year_second_player(890,red).
next_year_second_player(892,red).
next_year_second_player(894,red).
next_year_second_player(896,blue).
next_year_second_player(898,blue).
next_year_second_player(899,blue).
next_year_second_player(900,blue).
next_year_second_player(902,blue).
next_year_second_player(904,red).
next_year_second_player(906,red).
next_year_second_player(908,red).
next_year_second_player(910,red).
next_year_second_player(912,blue).
next_year_second_player(914,blue).
next_year_second_player(915,blue).
next_year_second_player(916,blue).
next_year_second_player(918,blue).
next_year_second_player(920,red).
next_year_second_player(922,red).
next_year_second_player(924,red).
next_year_second_player(926,red).
next_year_second_player(928,blue).
next_year_second_player(930,blue).
next_year_second_player(931,blue).
next_year_second_player(932,blue).
next_year_second_player(934,blue).
next_year_second_player(936,red).
next_year_second_player(938,red).
next_year_second_player(940,red).
next_year_second_player(942,red).
next_year_second_player(944,blue).
next_year_second_player(946,blue).
next_year_second_player(947,blue).
next_year_second_player(948,blue).
next_year_second_player(950,blue).
next_year_second_player(952,red).
next_year_second_player(954,red).
next_year_second_player(956,red).
next_year_second_player(958,red).
next_year_second_player(960,blue).
next_year_second_player(962,blue).
next_year_second_player(964,blue).
next_year_second_player(966,blue).
next_year_second_player(968,red).
next_year_second_player(970,red).
next_year_second_player(972,red).
next_year_second_player(974,red).
next_year_second_player(976,blue).
next_year_second_player(978,blue).
next_year_second_player(979,blue).
next_year_second_player(980,blue).
next_year_second_player(982,blue).
next_year_second_player(984,red).
next_year_second_player(986,red).
next_year_second_player(988,red).
next_year_second_player(990,red).
next_year_second_player(992,blue).
next_year_second_player(994,blue).
next_year_second_player(995,blue).
next_year_second_player(996,blue).
next_year_second_player(998,blue).
next_year_second_player(1000,red).
next_year_second_player(1002,red).
next_year_second_player(1004,red).
next_year_second_player(1006,red).
next_year_second_player(1008,blue).
next_year_second_player(1010,blue).
next_year_second_player(1011,blue).
next_year_second_player(1012,blue).
next_year_second_player(1014,blue).
next_year_second_player(1016,red).
next_year_second_player(1018,red).
next_year_second_player(1020,red).
next_year_second_player(1022,red).
next_year_second_player(1024,blue).
next_year_second_player(1026,blue).
next_year_second_player(1027,blue).
next_year_second_player(1028,blue).
next_year_second_player(1030,blue).
next_year_second_player(1032,red).
next_year_second_player(1034,red).
next_year_second_player(1036,red).
next_year_second_player(1038,red).
next_year_second_player(1039,red).
next_year_second_player(1040,blue).
next_year_second_player(1042,blue).
next_year_second_player(1044,blue).
next_year_second_player(1046,blue).
next_year_second_player(1048,red).
next_year_second_player(1050,red).
next_year_second_player(1052,red).
next_year_second_player(1054,red).
next_year_second_player(1056,blue).
next_year_second_player(1058,blue).
next_year_second_player(1059,blue).
next_year_second_player(1060,blue).
next_year_second_player(1062,blue).
next_year_second_player(1064,red).
next_year_second_player(1066,red).
next_year_second_player(1068,red).
next_year_second_player(1070,red).
next_year_second_player(1072,blue).
next_year_second_player(1074,blue).
next_year_second_player(1075,blue).
next_year_second_player(1076,blue).
next_year_second_player(1078,blue).
next_year_second_player(1080,red).
next_year_second_player(1082,red).
next_year_second_player(1084,red).
next_year_second_player(1086,red).
next_year_second_player(1088,blue).
next_year_second_player(1090,blue).
next_year_second_player(1091,blue).
next_year_second_player(1092,blue).
next_year_second_player(1094,blue).
next_year_second_player(1096,red).
next_year_second_player(1098,red).
next_year_second_player(1100,red).
next_year_second_player(1102,red).
next_year_second_player(1104,blue).
next_year_second_player(1106,blue).
next_year_second_player(1107,blue).
next_year_second_player(1108,blue).
next_year_second_player(1110,blue).
next_year_second_player(1112,red).
next_year_second_player(1113,red).
next_year_second_player(1114,red).
next_year_second_player(1116,red).
next_year_second_player(1118,red).
next_year_second_player(1120,blue).
next_year_second_player(1122,blue).
next_year_second_player(1124,blue).
next_year_second_player(1126,blue).
next_year_second_player(1128,red).
next_year_second_player(1130,red).
next_year_second_player(1132,red).
next_year_second_player(1134,red).
next_year_second_player(1136,blue).
next_year_second_player(1138,blue).
next_year_second_player(1139,blue).
next_year_second_player(1140,blue).
next_year_second_player(1142,blue).
next_year_second_player(1144,red).
next_year_second_player(1146,red).
next_year_second_player(1148,red).
next_year_second_player(1150,red).
next_year_second_player(1152,blue).
next_year_second_player(1154,blue).
next_year_second_player(1155,blue).
next_year_second_player(1156,blue).
next_year_second_player(1158,blue).
next_year_second_player(1160,red).
next_year_second_player(1162,red).
next_year_second_player(1164,red).
next_year_second_player(1166,red).
next_year_second_player(1168,blue).
next_year_second_player(1170,blue).
next_year_second_player(1171,blue).
next_year_second_player(1172,blue).
next_year_second_player(1174,blue).
next_year_second_player(1176,red).
next_year_second_player(1178,red).
next_year_second_player(1180,red).
next_year_second_player(1182,red).
next_year_second_player(1184,blue).
next_year_second_player(1186,blue).
next_year_second_player(1187,blue).
next_year_second_player(1188,blue).
next_year_second_player(1190,blue).
next_year_second_player(1192,red).
next_year_second_player(1194,red).
next_year_second_player(1195,red).
next_year_second_player(1196,red).
next_year_second_player(1198,red).
next_year_second_player(1200,blue).
next_year_second_player(1202,blue).
next_year_second_player(1204,blue).
next_year_second_player(1206,blue).
next_year_second_player(1208,red).
next_year_second_player(1210,red).
next_year_second_player(1212,red).
next_year_second_player(1214,red).
next_year_second_player(1216,blue).
next_year_second_player(1218,blue).
next_year_second_player(1219,blue).
next_year_second_player(1220,blue).
next_year_second_player(1222,blue).
next_year_second_player(1224,red).
next_year_second_player(1226,red).
next_year_second_player(1228,red).
next_year_second_player(1230,red).
next_year_second_player(1232,blue).
next_year_second_player(1234,blue).
next_year_second_player(1235,blue).
next_year_second_player(1236,blue).
next_year_second_player(1238,blue).
next_year_second_player(1240,red).
next_year_second_player(1242,red).
next_year_second_player(1244,red).
next_year_second_player(1246,red).
next_year_second_player(1248,blue).
next_year_second_player(1250,blue).
next_year_second_player(1251,blue).
next_year_second_player(1252,blue).
next_year_second_player(1254,blue).
next_year_second_player(1256,red).
next_year_second_player(1258,red).
next_year_second_player(1260,red).
next_year_second_player(1262,red).
next_year_second_player(1264,blue).
next_year_second_player(1266,blue).
next_year_second_player(1267,blue).
next_year_second_player(1268,blue).
next_year_second_player(1270,blue).
next_year_second_player(1272,red).
next_year_second_player(1274,red).
next_year_second_player(1275,red).
next_year_second_player(1276,red).
next_year_second_player(1278,red).
next_year_second_player(1280,blue).
next_year_second_player(1282,blue).
next_year_second_player(1284,blue).
next_year_second_player(1286,blue).
next_year_second_player(1288,red).
next_year_second_player(1290,red).
next_year_second_player(1292,red).
next_year_second_player(1294,red).
next_year_second_player(1296,blue).
next_year_second_player(1298,blue).
next_year_second_player(1299,blue).
next_year_second_player(1300,blue).
next_year_second_player(1302,blue).
next_year_second_player(1304,red).
next_year_second_player(1306,red).
next_year_second_player(1308,red).
next_year_second_player(1310,red).
next_year_second_player(1312,blue).
next_year_second_player(1314,blue).
next_year_second_player(1315,blue).
next_year_second_player(1316,blue).
next_year_second_player(1318,blue).
next_year_second_player(1320,red).
next_year_second_player(1322,red).
next_year_second_player(1324,red).
next_year_second_player(1326,red).
next_year_second_player(1328,blue).
next_year_second_player(1330,blue).
next_year_second_player(1331,blue).
next_year_second_player(1332,blue).
next_year_second_player(1334,blue).
next_year_second_player(1336,red).
next_year_second_player(1338,red).
next_year_second_player(1340,red).
next_year_second_player(1342,red).
next_year_second_player(1344,blue).
next_year_second_player(1346,blue).
next_year_second_player(1347,blue).
next_year_second_player(1348,blue).
next_year_second_player(1350,blue).
next_year_second_player(1352,red).
next_year_second_player(1353,red).
next_year_second_player(1354,red).
next_year_second_player(1356,red).
next_year_second_player(1358,red).
next_year_second_player(1360,blue).
next_year_second_player(1362,blue).
next_year_second_player(1364,blue).
next_year_second_player(1366,blue).
next_year_second_player(1368,red).
next_year_second_player(1370,red).
next_year_second_player(1372,red).
next_year_second_player(1374,red).
next_year_second_player(1376,blue).
next_year_second_player(1378,blue).
next_year_second_player(1379,blue).
next_year_second_player(1380,blue).
next_year_second_player(1382,blue).
next_year_second_player(1384,red).
next_year_second_player(1386,red).
next_year_second_player(1388,red).
next_year_second_player(1390,red).
next_year_second_player(1392,blue).
next_year_second_player(1394,blue).
next_year_second_player(1395,blue).
next_year_second_player(1396,blue).
next_year_second_player(1398,blue).
next_year_second_player(1400,red).
next_year_second_player(1402,red).
next_year_second_player(1404,red).
next_year_second_player(1406,red).
next_year_second_player(1408,blue).
next_year_second_player(1410,blue).
next_year_second_player(1411,blue).
next_year_second_player(1412,blue).
next_year_second_player(1414,blue).
next_year_second_player(1416,red).
next_year_second_player(1418,red).
next_year_second_player(1420,red).
next_year_second_player(1422,red).
next_year_second_player(1424,blue).
next_year_second_player(1426,blue).
next_year_second_player(1427,blue).
next_year_second_player(1428,blue).
next_year_second_player(1430,blue).
next_year_second_player(1432,red).
next_year_second_player(1434,red).
next_year_second_player(1435,red).
next_year_second_player(1436,red).
next_year_second_player(1438,red).
next_year_second_player(1440,blue).
next_year_second_player(1442,blue).
next_year_second_player(1444,blue).
next_year_second_player(1446,blue).
next_year_second_player(1448,red).
next_year_second_player(1450,red).
next_year_second_player(1452,red).
next_year_second_player(1454,red).
next_year_second_player(1456,blue).
next_year_second_player(1458,blue).
next_year_second_player(1459,blue).
next_year_second_player(1460,blue).
next_year_second_player(1462,blue).
next_year_second_player(1464,red).
next_year_second_player(1466,red).
next_year_second_player(1468,red).
next_year_second_player(1470,red).
next_year_second_player(1472,blue).
next_year_second_player(1474,blue).
next_year_second_player(1475,blue).
next_year_second_player(1476,blue).
next_year_second_player(1478,blue).
next_year_second_player(1480,red).
next_year_second_player(1482,red).
next_year_second_player(1484,red).
next_year_second_player(1486,red).
next_year_second_player(1488,blue).
next_year_second_player(1490,blue).
next_year_second_player(1491,blue).
next_year_second_player(1492,blue).
next_year_second_player(1494,blue).
next_year_second_player(1496,red).
next_year_second_player(1498,red).
next_year_second_player(1500,red).
next_year_second_player(1502,red).
next_year_second_player(1504,blue).
next_year_second_player(1506,blue).
next_year_second_player(1507,blue).
next_year_second_player(1508,blue).
next_year_second_player(1510,blue).
next_year_second_player(1512,red).
next_year_second_player(1514,red).
next_year_second_player(1515,red).
next_year_second_player(1516,red).
next_year_second_player(1518,red).
next_year_second_player(1520,blue).
next_year_second_player(1522,blue).
next_year_second_player(1524,blue).
next_year_second_player(1526,blue).
next_year_second_player(1528,red).
next_year_second_player(1530,red).
next_year_second_player(1532,red).
next_year_second_player(1534,red).
next_year_second_player(1536,blue).
next_year_second_player(1538,blue).
next_year_second_player(1539,blue).
next_year_second_player(1540,blue).
next_year_second_player(1542,blue).
next_year_second_player(1544,red).
next_year_second_player(1546,red).
next_year_second_player(1548,red).
next_year_second_player(1550,red).
next_year_second_player(1552,blue).
next_year_second_player(1554,blue).
next_year_second_player(1555,blue).
next_year_second_player(1556,blue).
next_year_second_player(1558,blue).
next_year_second_player(1560,red).
next_year_second_player(1562,red).
next_year_second_player(1564,red).
next_year_second_player(1566,red).
next_year_second_player(1568,blue).
next_year_second_player(1570,blue).
next_year_second_player(1571,blue).
next_year_second_player(1572,blue).
next_year_second_player(1574,blue).
next_year_second_player(1576,red).
next_year_second_player(1578,red).
next_year_second_player(1580,red).
next_year_second_player(1582,red).
next_year_second_player(1584,blue).
next_year_second_player(1586,blue).
next_year_second_player(1587,blue).
next_year_second_player(1588,blue).
next_year_second_player(1590,blue).
next_year_second_player(1592,red).
next_year_second_player(1594,red).
next_year_second_player(1595,red).
next_year_second_player(1596,red).
next_year_second_player(1598,red).
next_year_second_player(1600,blue).
next_year_second_player(1602,blue).
next_year_second_player(1604,blue).
next_year_second_player(1606,blue).
next_year_second_player(1608,red).
next_year_second_player(1610,red).
next_year_second_player(1612,red).
next_year_second_player(1614,red).
next_year_second_player(1616,blue).
next_year_second_player(1618,blue).
next_year_second_player(1619,blue).
next_year_second_player(1620,blue).
next_year_second_player(1622,blue).
next_year_second_player(1624,red).
next_year_second_player(1626,red).
next_year_second_player(1628,red).
next_year_second_player(1630,red).
next_year_second_player(1632,blue).
next_year_second_player(1634,blue).
next_year_second_player(1636,blue).
next_year_second_player(1637,blue).
next_year_second_player(1638,blue).
next_year_second_player(1640,red).
next_year_second_player(1642,red).
next_year_second_player(1644,red).
next_year_second_player(1646,red).
next_year_second_player(1648,blue).
next_year_second_player(1650,blue).
next_year_second_player(1651,blue).
next_year_second_player(1652,blue).
next_year_second_player(1654,blue).
next_year_second_player(1656,red).
next_year_second_player(1658,red).
next_year_second_player(1660,red).
next_year_second_player(1662,red).
next_year_second_player(1664,blue).
next_year_second_player(1666,blue).
next_year_second_player(1667,blue).
next_year_second_player(1668,blue).
next_year_second_player(1670,blue).
next_year_second_player(1672,red).
next_year_second_player(1674,red).
next_year_second_player(1676,red).
next_year_second_player(1677,red).
next_year_second_player(1678,red).
next_year_second_player(1680,blue).
next_year_second_player(1682,blue).
next_year_second_player(1684,blue).
next_year_second_player(1686,blue).
next_year_second_player(1688,red).
next_year_second_player(1690,red).
next_year_second_player(1692,red).
next_year_second_player(1694,red).
next_year_second_player(1696,blue).
next_year_second_player(1698,blue).
next_year_second_player(1699,blue).
next_year_second_player(1700,blue).
next_year_second_player(1702,blue).
next_year_second_player(1704,red).
next_year_second_player(1706,red).
next_year_second_player(1708,red).
next_year_second_player(1710,red).
next_year_second_player(1712,blue).
next_year_second_player(1714,blue).
next_year_second_player(1715,blue).
next_year_second_player(1716,blue).
next_year_second_player(1718,blue).
next_year_second_player(1720,red).
next_year_second_player(1722,red).
next_year_second_player(1724,red).
next_year_second_player(1726,red).
next_year_second_player(1728,blue).
next_year_second_player(1730,blue).
next_year_second_player(1731,blue).
next_year_second_player(1732,blue).
next_year_second_player(1734,blue).
next_year_second_player(1736,red).
next_year_second_player(1738,red).
next_year_second_player(1740,red).
next_year_second_player(1742,red).
next_year_second_player(1744,blue).
next_year_second_player(1746,blue).
next_year_second_player(1747,blue).
next_year_second_player(1748,blue).
next_year_second_player(1750,blue).
next_year_second_player(1752,red).
next_year_second_player(1754,red).
next_year_second_player(1755,red).
next_year_second_player(1756,red).
next_year_second_player(1758,red).
next_year_second_player(1760,blue).
next_year_second_player(1762,blue).
next_year_second_player(1764,blue).
next_year_second_player(1766,blue).
next_year_second_player(1768,red).
next_year_second_player(1770,red).
next_year_second_player(1772,red).
next_year_second_player(1774,red).
next_year_second_player(1776,blue).
next_year_second_player(1778,blue).
next_year_second_player(1779,blue).
next_year_second_player(1780,blue).
next_year_second_player(1782,blue).
next_year_second_player(1784,red).
next_year_second_player(1786,red).
next_year_second_player(1788,red).
next_year_second_player(1790,red).
next_year_second_player(1792,blue).
next_year_second_player(1794,blue).
next_year_second_player(1795,blue).
next_year_second_player(1796,blue).
next_year_second_player(1798,blue).
next_year_second_player(1800,red).
next_year_second_player(1802,red).
next_year_second_player(1804,red).
next_year_second_player(1806,red).
next_year_second_player(1808,blue).
next_year_second_player(1810,blue).
next_year_second_player(1811,blue).
next_year_second_player(1812,blue).
next_year_second_player(1814,blue).
next_year_second_player(1816,red).
next_year_second_player(1818,red).
next_year_second_player(1820,red).
next_year_second_player(1822,red).
next_year_second_player(1824,blue).
next_year_second_player(1826,blue).
next_year_second_player(1827,blue).
next_year_second_player(1828,blue).
next_year_second_player(1830,blue).
next_year_second_player(1832,red).
next_year_second_player(1834,red).
next_year_second_player(1835,red).
next_year_second_player(1836,red).
next_year_second_player(1838,red).
next_year_second_player(1840,blue).
next_year_second_player(1842,blue).
next_year_second_player(1844,blue).
next_year_second_player(1846,blue).
next_year_second_player(1848,red).
next_year_second_player(1850,red).
next_year_second_player(1852,red).
next_year_second_player(1854,red).
next_year_second_player(1856,blue).
next_year_second_player(1858,blue).
next_year_second_player(1859,blue).
next_year_second_player(1860,blue).
next_year_second_player(1862,blue).
next_year_second_player(1864,red).
next_year_second_player(1866,red).
next_year_second_player(1868,red).
next_year_second_player(1870,red).
next_year_second_player(1872,blue).
next_year_second_player(1874,blue).
next_year_second_player(1875,blue).
next_year_second_player(1876,blue).
next_year_second_player(1878,blue).
next_year_second_player(1880,red).
next_year_second_player(1882,red).
next_year_second_player(1884,red).
next_year_second_player(1886,red).
next_year_second_player(1888,blue).
next_year_second_player(1890,blue).
next_year_second_player(1891,blue).
next_year_second_player(1892,blue).
next_year_second_player(1894,blue).
next_year_second_player(1896,red).
next_year_second_player(1898,red).
next_year_second_player(1900,red).
next_year_second_player(1902,red).
next_year_second_player(1904,blue).
next_year_second_player(1906,blue).
next_year_second_player(1907,blue).
next_year_second_player(1908,blue).
next_year_second_player(1910,blue).
next_year_second_player(1912,red).
next_year_second_player(1913,red).
next_year_second_player(1914,red).
next_year_second_player(1916,red).
next_year_second_player(1918,red).
next_year_second_player(1920,blue).
