legal_b(1,robot).
legal_c(1,robot).
legal_a(1,robot).
legal_b(2,robot).
legal_c(2,robot).
legal_a(2,robot).
legal_b(3,robot).
legal_c(3,robot).
legal_a(3,robot).
legal_b(4,robot).
legal_c(4,robot).
legal_a(4,robot).
legal_b(5,robot).
legal_c(5,robot).
legal_a(5,robot).
legal_b(6,robot).
legal_c(6,robot).
legal_a(6,robot).
legal_b(7,robot).
legal_c(7,robot).
legal_a(7,robot).
