next_control(1,black).
next_control(2,white).
next_control(3,black).
next_control(4,white).
next_control(5,black).
next_control(6,white).
next_control(7,black).
next_control(8,white).
next_control(9,black).
next_control(10,white).
next_control(11,black).
next_control(12,white).
next_control(13,black).
next_control(14,white).
next_control(15,black).
next_control(16,white).
next_control(17,black).
next_control(18,white).
next_control(19,black).
next_control(20,white).
