next_season(1,winter).
next_season(2,spring).
next_season(3,spring).
next_season(4,summer).
next_season(5,summer).
next_season(6,fall).
next_season(7,fall).
next_season(8,winter).
next_season(9,winter).
next_season(10,spring).
next_season(11,spring).
next_season(12,summer).
next_season(13,summer).
next_season(14,fall).
next_season(15,fall).
next_season(16,winter).
next_season(17,winter).
next_season(18,spring).
next_season(19,spring).
next_season(20,summer).
next_season(21,summer).
next_season(22,fall).
next_season(23,fall).
next_season(24,winter).
next_season(25,winter).
next_season(26,spring).
next_season(27,spring).
next_season(28,summer).
next_season(29,summer).
next_season(30,fall).
next_season(31,fall).
next_season(32,winter).
next_season(33,winter).
next_season(34,spring).
next_season(35,spring).
next_season(36,summer).
next_season(37,summer).
next_season(38,fall).
next_season(39,fall).
next_season(40,winter).
next_season(41,winter).
next_season(42,spring).
next_season(43,spring).
next_season(44,summer).
next_season(45,summer).
next_season(46,fall).
next_season(47,fall).
next_season(48,winter).
next_season(49,winter).
next_season(50,spring).
next_season(51,spring).
next_season(52,summer).
next_season(53,summer).
next_season(54,fall).
next_season(55,fall).
next_season(56,winter).
next_season(57,winter).
next_season(58,spring).
next_season(59,spring).
next_season(60,summer).
next_season(61,summer).
next_season(62,fall).
next_season(63,fall).
next_season(64,winter).
next_season(65,winter).
next_season(66,spring).
next_season(67,spring).
next_season(68,summer).
next_season(69,summer).
next_season(70,fall).
next_season(71,fall).
next_season(72,winter).
next_season(73,winter).
next_season(74,spring).
next_season(75,spring).
next_season(76,summer).
next_season(77,summer).
next_season(78,fall).
next_season(79,fall).
next_season(80,winter).
