legal_offer(1,white,9).
legal_offer(1,white,3).
legal_offer(1,white,6).
legal_offer(1,white,1).
legal(1,black,noop).
legal_offer(1,white,2).
legal_offer(1,white,0).
legal_offer(1,white,7).
legal_offer(1,white,10).
legal_offer(1,white,5).
legal_offer(1,white,8).
legal_offer(1,white,4).
legal_offer(2,white,9).
legal_offer(2,white,3).
legal_offer(2,white,6).
legal_offer(2,white,1).
legal(2,black,noop).
legal_offer(2,white,2).
legal_offer(2,white,0).
legal_offer(2,white,7).
legal_offer(2,white,10).
legal_offer(2,white,5).
legal_offer(2,white,8).
legal_offer(2,white,4).
legal(3,black,reject).
legal(3,white,noop).
legal(3,black,accept).
legal_offer(4,white,9).
legal_offer(4,white,3).
legal_offer(4,white,6).
legal_offer(4,white,1).
legal(4,black,noop).
legal_offer(4,white,2).
legal_offer(4,white,0).
legal_offer(4,white,7).
legal_offer(4,white,10).
legal_offer(4,white,5).
legal_offer(4,white,8).
legal_offer(4,white,4).
legal(5,black,reject).
legal(5,white,noop).
legal(5,black,accept).
legal_offer(6,white,9).
legal_offer(6,white,3).
legal_offer(6,white,6).
legal_offer(6,white,1).
legal(6,black,noop).
legal_offer(6,white,2).
legal_offer(6,white,0).
legal_offer(6,white,7).
legal_offer(6,white,10).
legal_offer(6,white,5).
legal_offer(6,white,8).
legal_offer(6,white,4).
legal(7,black,reject).
legal(7,white,noop).
legal(7,black,accept).
legal_offer(8,white,9).
legal_offer(8,white,3).
legal_offer(8,white,6).
legal_offer(8,white,1).
legal(8,black,noop).
legal_offer(8,white,2).
legal_offer(8,white,0).
legal_offer(8,white,7).
legal_offer(8,white,10).
legal_offer(8,white,5).
legal_offer(8,white,8).
legal_offer(8,white,4).
legal(9,black,reject).
legal(9,white,noop).
legal(9,black,accept).
legal_offer(10,white,9).
legal_offer(10,white,3).
legal_offer(10,white,6).
legal_offer(10,white,1).
legal(10,black,noop).
legal_offer(10,white,2).
legal_offer(10,white,0).
legal_offer(10,white,7).
legal_offer(10,white,10).
legal_offer(10,white,5).
legal_offer(10,white,8).
legal_offer(10,white,4).
legal(11,black,reject).
legal(11,white,noop).
legal(11,black,accept).
legal_offer(12,white,9).
legal_offer(12,white,3).
legal_offer(12,white,6).
legal_offer(12,white,1).
legal(12,black,noop).
legal_offer(12,white,2).
legal_offer(12,white,0).
legal_offer(12,white,7).
legal_offer(12,white,10).
legal_offer(12,white,5).
legal_offer(12,white,8).
legal_offer(12,white,4).
legal(13,black,reject).
legal(13,white,noop).
legal(13,black,accept).
legal_offer(14,white,9).
legal_offer(14,white,3).
legal_offer(14,white,6).
legal_offer(14,white,1).
legal(14,black,noop).
legal_offer(14,white,2).
legal_offer(14,white,0).
legal_offer(14,white,7).
legal_offer(14,white,10).
legal_offer(14,white,5).
legal_offer(14,white,8).
legal_offer(14,white,4).
legal(15,black,reject).
legal(15,white,noop).
legal(15,black,accept).
legal_offer(16,white,9).
legal_offer(16,white,3).
legal_offer(16,white,6).
legal_offer(16,white,1).
legal(16,black,noop).
legal_offer(16,white,2).
legal_offer(16,white,0).
legal_offer(16,white,7).
legal_offer(16,white,10).
legal_offer(16,white,5).
legal_offer(16,white,8).
legal_offer(16,white,4).
legal(17,black,reject).
legal(17,white,noop).
legal(17,black,accept).
legal_offer(18,white,9).
legal_offer(18,white,3).
legal_offer(18,white,6).
legal_offer(18,white,1).
legal(18,black,noop).
legal_offer(18,white,2).
legal_offer(18,white,0).
legal_offer(18,white,7).
legal_offer(18,white,10).
legal_offer(18,white,5).
legal_offer(18,white,8).
legal_offer(18,white,4).
legal(19,black,reject).
legal(19,white,noop).
legal(19,black,accept).
legal_offer(20,white,9).
legal_offer(20,white,3).
legal_offer(20,white,6).
legal_offer(20,white,1).
legal(20,black,noop).
legal_offer(20,white,2).
legal_offer(20,white,0).
legal_offer(20,white,7).
legal_offer(20,white,10).
legal_offer(20,white,5).
legal_offer(20,white,8).
legal_offer(20,white,4).
legal(21,black,reject).
legal(21,white,noop).
legal(21,black,accept).
