next_year_second_player(A,B) :-
   my_input(A,B,C), does(A,B,C), my_true_year_second_player(A,B).
next_year_second_player(A,B) :-
   my_true_year_second_player(A,B), my_input_harvest_col(A,B,A).
next_year_second_player(6,blue).
next_year_second_player(8,red).
next_year_second_player(10,red).
next_year_second_player(12,red).
next_year_second_player(14,red).
next_year_second_player(16,blue).
next_year_second_player(18,blue).
next_year_second_player(19,blue).
next_year_second_player(20,blue).
next_year_second_player(22,blue).
next_year_second_player(24,red).
next_year_second_player(26,red).
next_year_second_player(28,red).
next_year_second_player(30,red).
next_year_second_player(32,blue).
next_year_second_player(34,blue).
next_year_second_player(35,blue).
next_year_second_player(36,blue).
next_year_second_player(38,blue).
next_year_second_player(40,red).
next_year_second_player(42,red).
next_year_second_player(44,red).
next_year_second_player(46,red).
next_year_second_player(48,blue).
next_year_second_player(50,blue).
next_year_second_player(51,blue).
next_year_second_player(52,blue).
next_year_second_player(54,blue).
next_year_second_player(56,red).
next_year_second_player(58,red).
next_year_second_player(60,red).
next_year_second_player(62,red).
next_year_second_player(64,blue).
next_year_second_player(66,blue).
next_year_second_player(67,blue).
next_year_second_player(68,blue).
next_year_second_player(70,blue).
next_year_second_player(72,red).
next_year_second_player(73,red).
next_year_second_player(74,red).
next_year_second_player(76,red).
next_year_second_player(78,red).
next_year_second_player(80,blue).
next_year_second_player(82,blue).
next_year_second_player(84,blue).
next_year_second_player(86,blue).
next_year_second_player(88,red).
next_year_second_player(90,red).
next_year_second_player(92,red).
next_year_second_player(94,red).
next_year_second_player(96,blue).
next_year_second_player(98,blue).
next_year_second_player(99,blue).
next_year_second_player(100,blue).
next_year_second_player(102,blue).
next_year_second_player(104,red).
next_year_second_player(106,red).
next_year_second_player(108,red).
next_year_second_player(110,red).
next_year_second_player(112,blue).
next_year_second_player(114,blue).
next_year_second_player(115,blue).
next_year_second_player(116,blue).
next_year_second_player(118,blue).
next_year_second_player(120,red).
next_year_second_player(122,red).
next_year_second_player(124,red).
next_year_second_player(126,red).
next_year_second_player(128,blue).
next_year_second_player(130,blue).
next_year_second_player(131,blue).
next_year_second_player(132,blue).
next_year_second_player(134,blue).
next_year_second_player(136,red).
next_year_second_player(138,red).
next_year_second_player(140,red).
next_year_second_player(142,red).
next_year_second_player(144,blue).
next_year_second_player(146,blue).
next_year_second_player(147,blue).
next_year_second_player(148,blue).
next_year_second_player(150,blue).
next_year_second_player(152,red).
next_year_second_player(154,red).
next_year_second_player(155,red).
next_year_second_player(156,red).
next_year_second_player(158,red).
next_year_second_player(160,blue).
next_year_second_player(162,blue).
next_year_second_player(164,blue).
next_year_second_player(166,blue).
next_year_second_player(168,red).
next_year_second_player(170,red).
next_year_second_player(172,red).
next_year_second_player(174,red).
next_year_second_player(176,blue).
next_year_second_player(178,blue).
next_year_second_player(179,blue).
next_year_second_player(180,blue).
next_year_second_player(182,blue).
next_year_second_player(184,red).
next_year_second_player(186,red).
next_year_second_player(188,red).
next_year_second_player(190,red).
next_year_second_player(192,blue).
next_year_second_player(194,blue).
next_year_second_player(195,blue).
next_year_second_player(196,blue).
next_year_second_player(198,blue).
next_year_second_player(200,red).
next_year_second_player(202,red).
next_year_second_player(204,red).
next_year_second_player(206,red).
next_year_second_player(208,blue).
next_year_second_player(210,blue).
next_year_second_player(211,blue).
next_year_second_player(212,blue).
next_year_second_player(214,blue).
next_year_second_player(216,red).
next_year_second_player(218,red).
next_year_second_player(220,red).
next_year_second_player(222,red).
next_year_second_player(224,blue).
next_year_second_player(226,blue).
next_year_second_player(227,blue).
next_year_second_player(228,blue).
next_year_second_player(230,blue).
next_year_second_player(232,red).
next_year_second_player(233,red).
next_year_second_player(234,red).
next_year_second_player(236,red).
next_year_second_player(238,red).
next_year_second_player(240,blue).
next_year_second_player(242,blue).
next_year_second_player(244,blue).
next_year_second_player(246,blue).
next_year_second_player(248,red).
next_year_second_player(250,red).
next_year_second_player(252,red).
next_year_second_player(254,red).
next_year_second_player(256,blue).
next_year_second_player(258,blue).
next_year_second_player(259,blue).
next_year_second_player(260,blue).
next_year_second_player(262,blue).
next_year_second_player(264,red).
next_year_second_player(266,red).
next_year_second_player(268,red).
next_year_second_player(270,red).
next_year_second_player(272,blue).
next_year_second_player(274,blue).
next_year_second_player(275,blue).
next_year_second_player(276,blue).
next_year_second_player(278,blue).
next_year_second_player(280,red).
next_year_second_player(282,red).
next_year_second_player(284,red).
next_year_second_player(286,red).
next_year_second_player(288,blue).
next_year_second_player(290,blue).
next_year_second_player(291,blue).
next_year_second_player(292,blue).
next_year_second_player(294,blue).
next_year_second_player(296,red).
next_year_second_player(298,red).
next_year_second_player(300,red).
next_year_second_player(302,red).
next_year_second_player(304,blue).
next_year_second_player(306,blue).
next_year_second_player(307,blue).
next_year_second_player(308,blue).
next_year_second_player(310,blue).
next_year_second_player(312,red).
next_year_second_player(314,red).
next_year_second_player(315,red).
next_year_second_player(316,red).
next_year_second_player(318,red).
next_year_second_player(320,blue).
next_year_second_player(322,blue).
next_year_second_player(324,blue).
next_year_second_player(326,blue).
next_year_second_player(328,red).
next_year_second_player(330,red).
next_year_second_player(332,red).
next_year_second_player(334,red).
next_year_second_player(336,blue).
next_year_second_player(338,blue).
next_year_second_player(339,blue).
next_year_second_player(340,blue).
next_year_second_player(342,blue).
next_year_second_player(344,red).
next_year_second_player(346,red).
next_year_second_player(348,red).
next_year_second_player(350,red).
next_year_second_player(352,blue).
next_year_second_player(354,blue).
next_year_second_player(355,blue).
next_year_second_player(356,blue).
next_year_second_player(358,blue).
next_year_second_player(360,red).
next_year_second_player(362,red).
next_year_second_player(364,red).
next_year_second_player(366,red).
next_year_second_player(368,blue).
next_year_second_player(370,blue).
next_year_second_player(371,blue).
next_year_second_player(372,blue).
next_year_second_player(374,blue).
next_year_second_player(376,red).
next_year_second_player(378,red).
next_year_second_player(380,red).
next_year_second_player(382,red).
next_year_second_player(384,blue).
next_year_second_player(386,blue).
next_year_second_player(387,blue).
next_year_second_player(388,blue).
next_year_second_player(390,blue).
next_year_second_player(392,red).
next_year_second_player(394,red).
next_year_second_player(395,red).
next_year_second_player(396,red).
next_year_second_player(398,red).
next_year_second_player(400,blue).
next_year_second_player(402,blue).
next_year_second_player(404,blue).
next_year_second_player(406,blue).
next_year_second_player(408,red).
next_year_second_player(410,red).
next_year_second_player(412,red).
next_year_second_player(414,red).
next_year_second_player(416,blue).
next_year_second_player(418,blue).
next_year_second_player(419,blue).
next_year_second_player(420,blue).
next_year_second_player(422,blue).
next_year_second_player(424,red).
next_year_second_player(426,red).
next_year_second_player(428,red).
next_year_second_player(430,red).
next_year_second_player(432,blue).
next_year_second_player(434,blue).
next_year_second_player(435,blue).
next_year_second_player(436,blue).
next_year_second_player(438,blue).
next_year_second_player(440,red).
next_year_second_player(442,red).
next_year_second_player(444,red).
next_year_second_player(446,red).
next_year_second_player(448,blue).
next_year_second_player(450,blue).
next_year_second_player(451,blue).
next_year_second_player(452,blue).
next_year_second_player(454,blue).
next_year_second_player(456,red).
next_year_second_player(458,red).
next_year_second_player(460,red).
next_year_second_player(462,red).
next_year_second_player(464,blue).
next_year_second_player(466,blue).
next_year_second_player(467,blue).
next_year_second_player(468,blue).
next_year_second_player(470,blue).
next_year_second_player(472,red).
next_year_second_player(474,red).
next_year_second_player(476,red).
next_year_second_player(478,red).
next_year_second_player(479,red).
next_year_second_player(480,blue).
next_year_second_player(482,blue).
next_year_second_player(484,blue).
next_year_second_player(486,blue).
next_year_second_player(488,red).
next_year_second_player(490,red).
next_year_second_player(492,red).
next_year_second_player(494,red).
next_year_second_player(496,blue).
next_year_second_player(498,blue).
next_year_second_player(499,blue).
next_year_second_player(500,blue).
next_year_second_player(502,blue).
next_year_second_player(504,red).
next_year_second_player(506,red).
next_year_second_player(508,red).
next_year_second_player(510,red).
next_year_second_player(512,blue).
next_year_second_player(514,blue).
next_year_second_player(515,blue).
next_year_second_player(516,blue).
next_year_second_player(518,blue).
next_year_second_player(520,red).
next_year_second_player(522,red).
next_year_second_player(524,red).
next_year_second_player(526,red).
next_year_second_player(528,blue).
next_year_second_player(530,blue).
next_year_second_player(531,blue).
next_year_second_player(532,blue).
next_year_second_player(534,blue).
next_year_second_player(536,red).
next_year_second_player(538,red).
next_year_second_player(540,red).
next_year_second_player(542,red).
next_year_second_player(544,blue).
next_year_second_player(546,blue).
next_year_second_player(547,blue).
next_year_second_player(548,blue).
next_year_second_player(550,blue).
next_year_second_player(552,red).
next_year_second_player(554,red).
next_year_second_player(555,red).
next_year_second_player(556,red).
next_year_second_player(558,red).
next_year_second_player(560,blue).
next_year_second_player(562,blue).
next_year_second_player(564,blue).
next_year_second_player(566,blue).
next_year_second_player(568,red).
next_year_second_player(570,red).
next_year_second_player(572,red).
next_year_second_player(574,red).
next_year_second_player(576,blue).
next_year_second_player(578,blue).
next_year_second_player(579,blue).
next_year_second_player(580,blue).
next_year_second_player(582,blue).
next_year_second_player(584,red).
next_year_second_player(586,red).
next_year_second_player(588,red).
next_year_second_player(590,red).
next_year_second_player(592,blue).
next_year_second_player(594,blue).
next_year_second_player(595,blue).
next_year_second_player(596,blue).
next_year_second_player(598,blue).
next_year_second_player(600,red).
next_year_second_player(602,red).
next_year_second_player(604,red).
next_year_second_player(606,red).
next_year_second_player(608,blue).
next_year_second_player(610,blue).
next_year_second_player(611,blue).
next_year_second_player(612,blue).
next_year_second_player(614,blue).
next_year_second_player(616,red).
next_year_second_player(618,red).
next_year_second_player(620,red).
next_year_second_player(622,red).
next_year_second_player(624,blue).
next_year_second_player(626,blue).
next_year_second_player(627,blue).
next_year_second_player(628,blue).
next_year_second_player(630,blue).
next_year_second_player(632,red).
next_year_second_player(634,red).
next_year_second_player(635,red).
next_year_second_player(636,red).
next_year_second_player(638,red).
next_year_second_player(640,blue).
