next_placecontrol(2,black).
next_placecontrol(4,red).
next_placecontrol(6,black).
next_placecontrol(8,red).
next_placecontrol(10,black).
next_placecontrol(12,red).
next_placecontrol(14,black).
next_placecontrol(16,red).
next_placecontrol(18,black).
next_placecontrol(20,red).
next_placecontrol(22,black).
next_placecontrol(24,red).
next_placecontrol(26,black).
next_placecontrol(28,red).
next_placecontrol(30,black).
next_placecontrol(32,red).
next_placecontrol(34,black).
next_placecontrol(36,red).
next_placecontrol(38,black).
next_placecontrol(40,red).
next_placecontrol(42,black).
next_placecontrol(44,red).
next_placecontrol(46,black).
next_placecontrol(48,red).
next_placecontrol(50,black).
next_placecontrol(52,red).
next_placecontrol(54,black).
next_placecontrol(56,red).
next_placecontrol(58,black).
next_placecontrol(60,black).
next_placecontrol(62,red).
next_placecontrol(64,black).
next_placecontrol(66,red).
next_placecontrol(68,black).
next_placecontrol(70,red).
next_placecontrol(72,black).
next_placecontrol(74,red).
next_placecontrol(76,black).
next_placecontrol(78,red).
next_placecontrol(80,black).
next_placecontrol(82,red).
next_placecontrol(84,black).
next_placecontrol(86,red).
next_placecontrol(88,black).
next_placecontrol(90,red).
next_placecontrol(92,black).
next_placecontrol(94,red).
next_placecontrol(96,black).
next_placecontrol(98,red).
next_placecontrol(100,black).
next_placecontrol(102,red).
next_placecontrol(104,black).
next_placecontrol(106,red).
next_placecontrol(108,black).
next_placecontrol(110,red).
next_placecontrol(112,black).
next_placecontrol(114,red).
next_placecontrol(116,black).
next_placecontrol(118,red).
next_placecontrol(120,black).
next_placecontrol(122,red).
next_placecontrol(124,black).
next_placecontrol(126,red).
next_placecontrol(128,black).
next_placecontrol(130,red).
next_placecontrol(132,black).
next_placecontrol(134,red).
next_placecontrol(136,black).
next_placecontrol(138,red).
next_placecontrol(140,black).
next_placecontrol(142,red).
next_placecontrol(144,black).
next_placecontrol(146,red).
next_placecontrol(148,black).
next_placecontrol(150,red).
next_placecontrol(152,black).
next_placecontrol(154,red).
next_placecontrol(156,black).
next_placecontrol(158,red).
next_placecontrol(160,black).
next_placecontrol(162,red).
next_placecontrol(164,black).
next_placecontrol(166,black).
next_placecontrol(168,red).
next_placecontrol(170,black).
next_placecontrol(172,red).
next_placecontrol(174,black).
next_placecontrol(176,red).
next_placecontrol(178,black).
next_placecontrol(180,red).
next_placecontrol(182,black).
next_placecontrol(184,red).
next_placecontrol(186,black).
next_placecontrol(188,red).
next_placecontrol(190,black).
next_placecontrol(192,red).
next_placecontrol(194,black).
next_placecontrol(196,red).
next_placecontrol(198,black).
next_placecontrol(200,red).
next_placecontrol(202,black).
next_placecontrol(204,red).
next_placecontrol(206,black).
next_placecontrol(208,red).
next_placecontrol(210,black).
next_placecontrol(212,red).
next_placecontrol(214,black).
next_placecontrol(216,red).
next_placecontrol(218,black).
next_placecontrol(220,red).
next_placecontrol(222,black).
next_placecontrol(225,black).
next_placecontrol(227,red).
next_placecontrol(229,black).
next_placecontrol(231,red).
next_placecontrol(233,black).
next_placecontrol(235,red).
next_placecontrol(237,black).
next_placecontrol(239,red).
next_placecontrol(241,black).
next_placecontrol(243,red).
next_placecontrol(245,black).
next_placecontrol(247,red).
next_placecontrol(249,black).
next_placecontrol(251,red).
next_placecontrol(253,black).
next_placecontrol(255,red).
next_placecontrol(257,black).
next_placecontrol(259,red).
next_placecontrol(261,black).
next_placecontrol(263,red).
next_placecontrol(265,black).
next_placecontrol(267,red).
next_placecontrol(269,black).
next_placecontrol(271,red).
next_placecontrol(273,black).
next_placecontrol(275,red).
next_placecontrol(277,black).
next_placecontrol(279,red).
next_placecontrol(281,black).
next_placecontrol(283,black).
next_placecontrol(285,red).
next_placecontrol(287,black).
next_placecontrol(289,red).
next_placecontrol(291,black).
next_placecontrol(293,red).
next_placecontrol(295,black).
next_placecontrol(297,red).
next_placecontrol(299,black).
next_placecontrol(301,red).
next_placecontrol(303,black).
next_placecontrol(305,red).
next_placecontrol(307,black).
next_placecontrol(309,red).
next_placecontrol(311,black).
next_placecontrol(313,red).
next_placecontrol(315,black).
next_placecontrol(317,red).
next_placecontrol(319,black).
next_placecontrol(321,red).
next_placecontrol(323,black).
next_placecontrol(325,red).
next_placecontrol(328,black).
next_placecontrol(330,red).
next_placecontrol(332,black).
next_placecontrol(334,red).
next_placecontrol(336,black).
next_placecontrol(338,red).
next_placecontrol(340,black).
next_placecontrol(342,red).
next_placecontrol(344,black).
next_placecontrol(346,red).
next_placecontrol(348,black).
next_placecontrol(350,red).
next_placecontrol(352,black).
next_placecontrol(354,red).
next_placecontrol(356,black).
next_placecontrol(358,red).
next_placecontrol(360,black).
next_placecontrol(362,red).
next_placecontrol(364,black).
next_placecontrol(366,red).
next_placecontrol(368,black).
next_placecontrol(370,red).
next_placecontrol(372,black).
next_placecontrol(374,red).
next_placecontrol(376,black).
next_placecontrol(378,red).
next_placecontrol(380,black).
next_placecontrol(382,red).
next_placecontrol(384,black).
next_placecontrol(386,red).
next_placecontrol(388,black).
next_placecontrol(390,red).
next_placecontrol(392,black).
next_placecontrol(394,red).
next_placecontrol(396,black).
next_placecontrol(398,red).
next_placecontrol(400,black).
next_placecontrol(402,red).
next_placecontrol(404,black).
next_placecontrol(406,red).
next_placecontrol(408,black).
next_placecontrol(410,red).
next_placecontrol(412,black).
next_placecontrol(414,red).
next_placecontrol(416,black).
next_placecontrol(418,red).
next_placecontrol(420,black).
next_placecontrol(422,red).
next_placecontrol(424,black).
next_placecontrol(426,red).
next_placecontrol(428,black).
next_placecontrol(430,red).
next_placecontrol(432,black).
