legal(1,robot,b).
legal(1,robot,f).
legal(1,robot,d).
legal(1,robot,h).
legal(1,robot,a).
legal(1,robot,g).
legal(1,robot,c).
legal(1,robot,e).
legal(2,robot,b).
legal(2,robot,f).
legal(2,robot,d).
legal(2,robot,h).
legal(2,robot,a).
legal(2,robot,g).
legal(2,robot,c).
legal(2,robot,e).
legal(3,robot,b).
legal(3,robot,f).
legal(3,robot,d).
legal(3,robot,h).
legal(3,robot,a).
legal(3,robot,g).
legal(3,robot,c).
legal(3,robot,e).
legal(4,robot,b).
legal(4,robot,f).
legal(4,robot,d).
legal(4,robot,h).
legal(4,robot,a).
legal(4,robot,g).
legal(4,robot,c).
legal(4,robot,e).
legal(5,robot,b).
legal(5,robot,f).
legal(5,robot,d).
legal(5,robot,h).
legal(5,robot,a).
legal(5,robot,g).
legal(5,robot,c).
legal(5,robot,e).
legal(6,robot,b).
legal(6,robot,f).
legal(6,robot,d).
legal(6,robot,h).
legal(6,robot,a).
legal(6,robot,g).
legal(6,robot,c).
legal(6,robot,e).
legal(7,robot,b).
legal(7,robot,f).
legal(7,robot,d).
legal(7,robot,h).
legal(7,robot,a).
legal(7,robot,g).
legal(7,robot,c).
legal(7,robot,e).
legal(8,robot,b).
legal(8,robot,f).
legal(8,robot,d).
legal(8,robot,h).
legal(8,robot,a).
legal(8,robot,g).
legal(8,robot,c).
legal(8,robot,e).
legal(9,robot,b).
legal(9,robot,f).
legal(9,robot,d).
legal(9,robot,h).
legal(9,robot,a).
legal(9,robot,g).
legal(9,robot,c).
legal(9,robot,e).
legal(10,robot,b).
legal(10,robot,f).
legal(10,robot,d).
legal(10,robot,h).
legal(10,robot,a).
legal(10,robot,g).
legal(10,robot,c).
legal(10,robot,e).
legal(11,robot,b).
legal(11,robot,f).
legal(11,robot,d).
legal(11,robot,h).
legal(11,robot,a).
legal(11,robot,g).
legal(11,robot,c).
legal(11,robot,e).
legal(12,robot,b).
legal(12,robot,f).
legal(12,robot,d).
legal(12,robot,h).
legal(12,robot,a).
legal(12,robot,g).
legal(12,robot,c).
legal(12,robot,e).
legal(13,robot,b).
legal(13,robot,f).
legal(13,robot,d).
legal(13,robot,h).
legal(13,robot,a).
legal(13,robot,g).
legal(13,robot,c).
legal(13,robot,e).
legal(14,robot,b).
legal(14,robot,f).
legal(14,robot,d).
legal(14,robot,h).
legal(14,robot,a).
legal(14,robot,g).
legal(14,robot,c).
legal(14,robot,e).
legal(15,robot,b).
legal(15,robot,f).
legal(15,robot,d).
legal(15,robot,h).
legal(15,robot,a).
legal(15,robot,g).
legal(15,robot,c).
legal(15,robot,e).
legal(16,robot,b).
legal(16,robot,f).
legal(16,robot,d).
legal(16,robot,h).
legal(16,robot,a).
legal(16,robot,g).
legal(16,robot,c).
legal(16,robot,e).
legal(17,robot,b).
legal(17,robot,f).
legal(17,robot,d).
legal(17,robot,h).
legal(17,robot,a).
legal(17,robot,g).
legal(17,robot,c).
legal(17,robot,e).
legal(18,robot,b).
legal(18,robot,f).
legal(18,robot,d).
legal(18,robot,h).
legal(18,robot,a).
legal(18,robot,g).
legal(18,robot,c).
legal(18,robot,e).
legal(19,robot,b).
legal(19,robot,f).
legal(19,robot,d).
legal(19,robot,h).
legal(19,robot,a).
legal(19,robot,g).
legal(19,robot,c).
legal(19,robot,e).
legal(20,robot,b).
legal(20,robot,f).
legal(20,robot,d).
legal(20,robot,h).
legal(20,robot,a).
legal(20,robot,g).
legal(20,robot,c).
legal(20,robot,e).
legal(21,robot,b).
legal(21,robot,f).
legal(21,robot,d).
legal(21,robot,h).
legal(21,robot,a).
legal(21,robot,g).
legal(21,robot,c).
legal(21,robot,e).
legal(22,robot,b).
legal(22,robot,f).
legal(22,robot,d).
legal(22,robot,h).
legal(22,robot,a).
legal(22,robot,g).
legal(22,robot,c).
legal(22,robot,e).
legal(23,robot,b).
legal(23,robot,f).
legal(23,robot,d).
legal(23,robot,h).
legal(23,robot,a).
legal(23,robot,g).
legal(23,robot,c).
legal(23,robot,e).
legal(24,robot,b).
legal(24,robot,f).
legal(24,robot,d).
legal(24,robot,h).
legal(24,robot,a).
legal(24,robot,g).
legal(24,robot,c).
legal(24,robot,e).
legal(25,robot,b).
legal(25,robot,f).
legal(25,robot,d).
legal(25,robot,h).
legal(25,robot,a).
legal(25,robot,g).
legal(25,robot,c).
legal(25,robot,e).
legal(26,robot,b).
legal(26,robot,f).
legal(26,robot,d).
legal(26,robot,h).
legal(26,robot,a).
legal(26,robot,g).
legal(26,robot,c).
legal(26,robot,e).
legal(27,robot,b).
legal(27,robot,f).
legal(27,robot,d).
legal(27,robot,h).
legal(27,robot,a).
legal(27,robot,g).
legal(27,robot,c).
legal(27,robot,e).
legal(28,robot,b).
legal(28,robot,f).
legal(28,robot,d).
legal(28,robot,h).
legal(28,robot,a).
legal(28,robot,g).
legal(28,robot,c).
legal(28,robot,e).
legal(29,robot,b).
legal(29,robot,f).
legal(29,robot,d).
legal(29,robot,h).
legal(29,robot,a).
legal(29,robot,g).
legal(29,robot,c).
legal(29,robot,e).
legal(30,robot,b).
legal(30,robot,f).
legal(30,robot,d).
legal(30,robot,h).
legal(30,robot,a).
legal(30,robot,g).
legal(30,robot,c).
legal(30,robot,e).
legal(31,robot,b).
legal(31,robot,f).
legal(31,robot,d).
legal(31,robot,h).
legal(31,robot,a).
legal(31,robot,g).
legal(31,robot,c).
legal(31,robot,e).
legal(32,robot,b).
legal(32,robot,f).
legal(32,robot,d).
legal(32,robot,h).
legal(32,robot,a).
legal(32,robot,g).
legal(32,robot,c).
legal(32,robot,e).
legal(33,robot,b).
legal(33,robot,f).
legal(33,robot,d).
legal(33,robot,h).
legal(33,robot,a).
legal(33,robot,g).
legal(33,robot,c).
legal(33,robot,e).
legal(34,robot,b).
legal(34,robot,f).
legal(34,robot,d).
legal(34,robot,h).
legal(34,robot,a).
legal(34,robot,g).
legal(34,robot,c).
legal(34,robot,e).
legal(35,robot,b).
legal(35,robot,f).
legal(35,robot,d).
legal(35,robot,h).
legal(35,robot,a).
legal(35,robot,g).
legal(35,robot,c).
legal(35,robot,e).
legal(36,robot,b).
legal(36,robot,f).
legal(36,robot,d).
legal(36,robot,h).
legal(36,robot,a).
legal(36,robot,g).
legal(36,robot,c).
legal(36,robot,e).
legal(37,robot,b).
legal(37,robot,f).
legal(37,robot,d).
legal(37,robot,h).
legal(37,robot,a).
legal(37,robot,g).
legal(37,robot,c).
legal(37,robot,e).
legal(38,robot,b).
legal(38,robot,f).
legal(38,robot,d).
legal(38,robot,h).
legal(38,robot,a).
legal(38,robot,g).
legal(38,robot,c).
legal(38,robot,e).
legal(39,robot,b).
legal(39,robot,f).
legal(39,robot,d).
legal(39,robot,h).
legal(39,robot,a).
legal(39,robot,g).
legal(39,robot,c).
legal(39,robot,e).
legal(40,robot,b).
legal(40,robot,f).
legal(40,robot,d).
legal(40,robot,h).
legal(40,robot,a).
legal(40,robot,g).
legal(40,robot,c).
legal(40,robot,e).
legal(41,robot,b).
legal(41,robot,f).
legal(41,robot,d).
legal(41,robot,h).
legal(41,robot,a).
legal(41,robot,g).
legal(41,robot,c).
legal(41,robot,e).
legal(42,robot,b).
legal(42,robot,f).
legal(42,robot,d).
legal(42,robot,h).
legal(42,robot,a).
legal(42,robot,g).
legal(42,robot,c).
legal(42,robot,e).
legal(43,robot,b).
legal(43,robot,f).
legal(43,robot,d).
legal(43,robot,h).
legal(43,robot,a).
legal(43,robot,g).
legal(43,robot,c).
legal(43,robot,e).
legal(44,robot,b).
legal(44,robot,f).
legal(44,robot,d).
legal(44,robot,h).
legal(44,robot,a).
legal(44,robot,g).
legal(44,robot,c).
legal(44,robot,e).
legal(45,robot,b).
legal(45,robot,f).
legal(45,robot,d).
legal(45,robot,h).
legal(45,robot,a).
legal(45,robot,g).
legal(45,robot,c).
legal(45,robot,e).
legal(46,robot,b).
legal(46,robot,f).
legal(46,robot,d).
legal(46,robot,h).
legal(46,robot,a).
legal(46,robot,g).
legal(46,robot,c).
legal(46,robot,e).
legal(47,robot,b).
legal(47,robot,f).
legal(47,robot,d).
legal(47,robot,h).
legal(47,robot,a).
legal(47,robot,g).
legal(47,robot,c).
legal(47,robot,e).
legal(48,robot,b).
legal(48,robot,f).
legal(48,robot,d).
legal(48,robot,h).
legal(48,robot,a).
legal(48,robot,g).
legal(48,robot,c).
legal(48,robot,e).
legal(49,robot,b).
legal(49,robot,f).
legal(49,robot,d).
legal(49,robot,h).
legal(49,robot,a).
legal(49,robot,g).
legal(49,robot,c).
legal(49,robot,e).
legal(50,robot,b).
legal(50,robot,f).
legal(50,robot,d).
legal(50,robot,h).
legal(50,robot,a).
legal(50,robot,g).
legal(50,robot,c).
legal(50,robot,e).
legal(51,robot,b).
legal(51,robot,f).
legal(51,robot,d).
legal(51,robot,h).
legal(51,robot,a).
legal(51,robot,g).
legal(51,robot,c).
legal(51,robot,e).
legal(52,robot,b).
legal(52,robot,f).
legal(52,robot,d).
legal(52,robot,h).
legal(52,robot,a).
legal(52,robot,g).
legal(52,robot,c).
legal(52,robot,e).
legal(53,robot,b).
legal(53,robot,f).
legal(53,robot,d).
legal(53,robot,h).
legal(53,robot,a).
legal(53,robot,g).
legal(53,robot,c).
legal(53,robot,e).
legal(54,robot,b).
legal(54,robot,f).
legal(54,robot,d).
legal(54,robot,h).
legal(54,robot,a).
legal(54,robot,g).
legal(54,robot,c).
legal(54,robot,e).
legal(55,robot,b).
legal(55,robot,f).
legal(55,robot,d).
legal(55,robot,h).
legal(55,robot,a).
legal(55,robot,g).
legal(55,robot,c).
legal(55,robot,e).
legal(56,robot,b).
legal(56,robot,f).
legal(56,robot,d).
legal(56,robot,h).
legal(56,robot,a).
legal(56,robot,g).
legal(56,robot,c).
legal(56,robot,e).
legal(57,robot,b).
legal(57,robot,f).
legal(57,robot,d).
legal(57,robot,h).
legal(57,robot,a).
legal(57,robot,g).
legal(57,robot,c).
legal(57,robot,e).
legal(58,robot,b).
legal(58,robot,f).
legal(58,robot,d).
legal(58,robot,h).
legal(58,robot,a).
legal(58,robot,g).
legal(58,robot,c).
legal(58,robot,e).
legal(59,robot,b).
legal(59,robot,f).
legal(59,robot,d).
legal(59,robot,h).
legal(59,robot,a).
legal(59,robot,g).
legal(59,robot,c).
legal(59,robot,e).
legal(60,robot,b).
legal(60,robot,f).
legal(60,robot,d).
legal(60,robot,h).
legal(60,robot,a).
legal(60,robot,g).
legal(60,robot,c).
legal(60,robot,e).
legal(61,robot,b).
legal(61,robot,f).
legal(61,robot,d).
legal(61,robot,h).
legal(61,robot,a).
legal(61,robot,g).
legal(61,robot,c).
legal(61,robot,e).
legal(62,robot,b).
legal(62,robot,f).
legal(62,robot,d).
legal(62,robot,h).
legal(62,robot,a).
legal(62,robot,g).
legal(62,robot,c).
legal(62,robot,e).
legal(63,robot,b).
legal(63,robot,f).
legal(63,robot,d).
legal(63,robot,h).
legal(63,robot,a).
legal(63,robot,g).
legal(63,robot,c).
legal(63,robot,e).
legal(64,robot,b).
legal(64,robot,f).
legal(64,robot,d).
legal(64,robot,h).
legal(64,robot,a).
legal(64,robot,g).
legal(64,robot,c).
legal(64,robot,e).
