next_cell(1,c,red).
next_cell(1,a,blank).
next_cell(1,e,black).
next_cell(1,d,red).
next_cell(1,b,black).
next_cell(2,c,red).
next_cell(2,a,black).
next_cell(2,b,blank).
next_cell(2,e,black).
next_cell(2,d,red).
next_cell(3,a,black).
next_cell(3,b,red).
next_cell(3,c,blank).
next_cell(3,e,black).
next_cell(3,d,red).
next_cell(4,e,blank).
next_cell(4,a,black).
next_cell(4,b,red).
next_cell(4,c,black).
next_cell(4,d,red).
next_cell(5,a,black).
next_cell(5,b,red).
next_cell(5,d,blank).
next_cell(5,e,red).
next_cell(5,c,black).
next_cell(6,a,black).
next_cell(6,d,black).
next_cell(6,b,red).
next_cell(6,c,blank).
next_cell(6,e,red).
next_cell(7,c,red).
next_cell(7,a,black).
next_cell(7,e,blank).
next_cell(7,d,black).
next_cell(7,b,red).
next_cell(8,c,red).
next_cell(8,a,black).
next_cell(8,b,red).
next_cell(8,d,blank).
next_cell(8,e,black).
next_cell(9,a,black).
next_cell(9,b,red).
next_cell(9,c,blank).
next_cell(9,e,black).
next_cell(9,d,red).
next_cell(10,b,red).
next_cell(10,c,black).
next_cell(10,a,blank).
next_cell(10,e,black).
next_cell(10,d,red).
next_cell(11,a,red).
next_cell(11,c,black).
next_cell(11,b,blank).
next_cell(11,e,black).
next_cell(11,d,red).
next_cell(12,c,blank).
next_cell(12,a,red).
next_cell(12,e,black).
next_cell(12,d,red).
next_cell(12,b,black).
next_cell(13,c,red).
next_cell(13,d,blank).
next_cell(13,a,red).
next_cell(13,e,black).
next_cell(13,b,black).
next_cell(14,c,red).
next_cell(14,e,blank).
next_cell(14,d,black).
next_cell(14,a,red).
next_cell(14,b,black).
next_cell(15,d,black).
next_cell(15,c,blank).
next_cell(15,a,red).
next_cell(15,e,red).
next_cell(15,b,black).
next_cell(16,d,blank).
next_cell(16,a,red).
next_cell(16,e,red).
next_cell(16,c,black).
next_cell(16,b,black).
next_cell(17,e,blank).
next_cell(17,a,red).
next_cell(17,c,black).
next_cell(17,d,red).
next_cell(17,b,black).
next_cell(18,c,blank).
next_cell(18,a,red).
next_cell(18,e,black).
next_cell(18,d,red).
next_cell(18,b,black).
next_cell(19,c,red).
next_cell(19,a,blank).
next_cell(19,e,black).
next_cell(19,d,red).
next_cell(19,b,black).
