legal_drop(1,white,4).
legal_drop(1,white,5).
legal_drop(1,white,3).
legal_drop(2,white,4).
legal_drop(2,white,5).
legal_drop(2,white,3).
legal_drop(3,black,5).
legal_drop(3,black,3).
legal_drop(3,black,4).
legal_drop(4,white,4).
legal_drop(4,white,5).
legal_drop(4,white,3).
legal_drop(5,black,5).
legal_drop(5,black,3).
legal_drop(5,black,4).
legal_drop(6,white,4).
legal_drop(6,white,5).
legal_drop(6,white,3).
legal_drop(7,black,5).
legal_drop(7,black,3).
legal_drop(7,black,4).
legal_drop(8,white,4).
legal_drop(8,white,5).
legal_drop(8,white,3).
