legal_rotate(3,red,2,clockwise).
legal_rotate(3,red,3,counterclockwise).
legal_rotate(3,red,4,clockwise).
legal_rotate(3,red,2,counterclockwise).
legal_rotate(3,red,4,counterclockwise).
legal_rotate(3,red,1,counterclockwise).
legal_rotate(3,red,3,clockwise).
legal_rotate(3,red,1,clockwise).
legal_rotate(5,black,4,counterclockwise).
legal_rotate(5,black,1,counterclockwise).
legal_rotate(5,black,3,clockwise).
legal_rotate(5,black,2,counterclockwise).
legal_rotate(5,black,1,clockwise).
legal_rotate(5,black,3,counterclockwise).
legal_rotate(5,black,4,clockwise).
legal_rotate(5,black,2,clockwise).
legal_rotate(7,red,2,clockwise).
legal_rotate(7,red,3,counterclockwise).
legal_rotate(7,red,4,clockwise).
legal_rotate(7,red,2,counterclockwise).
legal_rotate(7,red,4,counterclockwise).
legal_rotate(7,red,1,counterclockwise).
legal_rotate(7,red,3,clockwise).
legal_rotate(7,red,1,clockwise).
legal_rotate(9,black,4,counterclockwise).
legal_rotate(9,black,1,counterclockwise).
legal_rotate(9,black,3,clockwise).
legal_rotate(9,black,2,counterclockwise).
legal_rotate(9,black,1,clockwise).
legal_rotate(9,black,3,counterclockwise).
legal_rotate(9,black,4,clockwise).
legal_rotate(9,black,2,clockwise).
legal_rotate(11,red,2,clockwise).
legal_rotate(11,red,3,counterclockwise).
legal_rotate(11,red,4,clockwise).
legal_rotate(11,red,2,counterclockwise).
legal_rotate(11,red,4,counterclockwise).
legal_rotate(11,red,1,counterclockwise).
legal_rotate(11,red,3,clockwise).
legal_rotate(11,red,1,clockwise).
legal_rotate(13,black,4,counterclockwise).
legal_rotate(13,black,1,counterclockwise).
legal_rotate(13,black,3,clockwise).
legal_rotate(13,black,2,counterclockwise).
legal_rotate(13,black,1,clockwise).
legal_rotate(13,black,3,counterclockwise).
legal_rotate(13,black,4,clockwise).
legal_rotate(13,black,2,clockwise).
legal_rotate(15,red,2,clockwise).
legal_rotate(15,red,3,counterclockwise).
legal_rotate(15,red,4,clockwise).
legal_rotate(15,red,2,counterclockwise).
legal_rotate(15,red,4,counterclockwise).
legal_rotate(15,red,1,counterclockwise).
legal_rotate(15,red,3,clockwise).
legal_rotate(15,red,1,clockwise).
legal_rotate(17,black,4,counterclockwise).
legal_rotate(17,black,1,counterclockwise).
legal_rotate(17,black,3,clockwise).
legal_rotate(17,black,2,counterclockwise).
legal_rotate(17,black,1,clockwise).
legal_rotate(17,black,3,counterclockwise).
legal_rotate(17,black,4,clockwise).
legal_rotate(17,black,2,clockwise).
legal_rotate(19,red,2,clockwise).
legal_rotate(19,red,3,counterclockwise).
legal_rotate(19,red,4,clockwise).
legal_rotate(19,red,2,counterclockwise).
legal_rotate(19,red,4,counterclockwise).
legal_rotate(19,red,1,counterclockwise).
legal_rotate(19,red,3,clockwise).
legal_rotate(19,red,1,clockwise).
legal_rotate(21,black,4,counterclockwise).
legal_rotate(21,black,1,counterclockwise).
legal_rotate(21,black,3,clockwise).
legal_rotate(21,black,2,counterclockwise).
legal_rotate(21,black,1,clockwise).
legal_rotate(21,black,3,counterclockwise).
legal_rotate(21,black,4,clockwise).
legal_rotate(21,black,2,clockwise).
legal_rotate(23,red,2,clockwise).
legal_rotate(23,red,3,counterclockwise).
legal_rotate(23,red,4,clockwise).
legal_rotate(23,red,2,counterclockwise).
legal_rotate(23,red,4,counterclockwise).
legal_rotate(23,red,1,counterclockwise).
legal_rotate(23,red,3,clockwise).
legal_rotate(23,red,1,clockwise).
legal_rotate(25,black,4,counterclockwise).
legal_rotate(25,black,1,counterclockwise).
legal_rotate(25,black,3,clockwise).
legal_rotate(25,black,2,counterclockwise).
legal_rotate(25,black,1,clockwise).
legal_rotate(25,black,3,counterclockwise).
legal_rotate(25,black,4,clockwise).
legal_rotate(25,black,2,clockwise).
legal_rotate(27,red,2,clockwise).
legal_rotate(27,red,3,counterclockwise).
legal_rotate(27,red,4,clockwise).
legal_rotate(27,red,2,counterclockwise).
legal_rotate(27,red,4,counterclockwise).
legal_rotate(27,red,1,counterclockwise).
legal_rotate(27,red,3,clockwise).
legal_rotate(27,red,1,clockwise).
legal_rotate(29,black,4,counterclockwise).
legal_rotate(29,black,1,counterclockwise).
legal_rotate(29,black,3,clockwise).
legal_rotate(29,black,2,counterclockwise).
legal_rotate(29,black,1,clockwise).
legal_rotate(29,black,3,counterclockwise).
legal_rotate(29,black,4,clockwise).
legal_rotate(29,black,2,clockwise).
legal_rotate(31,red,2,clockwise).
legal_rotate(31,red,3,counterclockwise).
legal_rotate(31,red,4,clockwise).
legal_rotate(31,red,2,counterclockwise).
legal_rotate(31,red,4,counterclockwise).
legal_rotate(31,red,1,counterclockwise).
legal_rotate(31,red,3,clockwise).
legal_rotate(31,red,1,clockwise).
legal_rotate(33,black,4,counterclockwise).
legal_rotate(33,black,1,counterclockwise).
legal_rotate(33,black,3,clockwise).
legal_rotate(33,black,2,counterclockwise).
legal_rotate(33,black,1,clockwise).
legal_rotate(33,black,3,counterclockwise).
legal_rotate(33,black,4,clockwise).
legal_rotate(33,black,2,clockwise).
legal_rotate(35,red,2,clockwise).
legal_rotate(35,red,3,counterclockwise).
legal_rotate(35,red,4,clockwise).
legal_rotate(35,red,2,counterclockwise).
legal_rotate(35,red,4,counterclockwise).
legal_rotate(35,red,1,counterclockwise).
legal_rotate(35,red,3,clockwise).
legal_rotate(35,red,1,clockwise).
legal_rotate(37,black,4,counterclockwise).
legal_rotate(37,black,1,counterclockwise).
legal_rotate(37,black,3,clockwise).
legal_rotate(37,black,2,counterclockwise).
legal_rotate(37,black,1,clockwise).
legal_rotate(37,black,3,counterclockwise).
legal_rotate(37,black,4,clockwise).
legal_rotate(37,black,2,clockwise).
legal_rotate(39,red,2,clockwise).
legal_rotate(39,red,3,counterclockwise).
legal_rotate(39,red,4,clockwise).
legal_rotate(39,red,2,counterclockwise).
legal_rotate(39,red,4,counterclockwise).
legal_rotate(39,red,1,counterclockwise).
legal_rotate(39,red,3,clockwise).
legal_rotate(39,red,1,clockwise).
legal_rotate(41,black,4,counterclockwise).
legal_rotate(41,black,1,counterclockwise).
legal_rotate(41,black,3,clockwise).
legal_rotate(41,black,2,counterclockwise).
legal_rotate(41,black,1,clockwise).
legal_rotate(41,black,3,counterclockwise).
legal_rotate(41,black,4,clockwise).
legal_rotate(41,black,2,clockwise).
legal_rotate(43,red,2,clockwise).
legal_rotate(43,red,3,counterclockwise).
legal_rotate(43,red,4,clockwise).
legal_rotate(43,red,2,counterclockwise).
legal_rotate(43,red,4,counterclockwise).
legal_rotate(43,red,1,counterclockwise).
legal_rotate(43,red,3,clockwise).
legal_rotate(43,red,1,clockwise).
legal_rotate(45,black,4,counterclockwise).
legal_rotate(45,black,1,counterclockwise).
legal_rotate(45,black,3,clockwise).
legal_rotate(45,black,2,counterclockwise).
legal_rotate(45,black,1,clockwise).
legal_rotate(45,black,3,counterclockwise).
legal_rotate(45,black,4,clockwise).
legal_rotate(45,black,2,clockwise).
legal_rotate(47,red,2,clockwise).
legal_rotate(47,red,3,counterclockwise).
legal_rotate(47,red,4,clockwise).
legal_rotate(47,red,2,counterclockwise).
legal_rotate(47,red,4,counterclockwise).
legal_rotate(47,red,1,counterclockwise).
legal_rotate(47,red,3,clockwise).
legal_rotate(47,red,1,clockwise).
legal_rotate(49,black,4,counterclockwise).
legal_rotate(49,black,1,counterclockwise).
legal_rotate(49,black,3,clockwise).
legal_rotate(49,black,2,counterclockwise).
legal_rotate(49,black,1,clockwise).
legal_rotate(49,black,3,counterclockwise).
legal_rotate(49,black,4,clockwise).
legal_rotate(49,black,2,clockwise).
legal_rotate(51,red,2,clockwise).
legal_rotate(51,red,3,counterclockwise).
legal_rotate(51,red,4,clockwise).
legal_rotate(51,red,2,counterclockwise).
legal_rotate(51,red,4,counterclockwise).
legal_rotate(51,red,1,counterclockwise).
legal_rotate(51,red,3,clockwise).
legal_rotate(51,red,1,clockwise).
legal_rotate(53,black,4,counterclockwise).
legal_rotate(53,black,1,counterclockwise).
legal_rotate(53,black,3,clockwise).
legal_rotate(53,black,2,counterclockwise).
legal_rotate(53,black,1,clockwise).
legal_rotate(53,black,3,counterclockwise).
legal_rotate(53,black,4,clockwise).
legal_rotate(53,black,2,clockwise).
legal_rotate(55,red,2,clockwise).
legal_rotate(55,red,3,counterclockwise).
legal_rotate(55,red,4,clockwise).
legal_rotate(55,red,2,counterclockwise).
legal_rotate(55,red,4,counterclockwise).
legal_rotate(55,red,1,counterclockwise).
legal_rotate(55,red,3,clockwise).
legal_rotate(55,red,1,clockwise).
legal_rotate(57,black,4,counterclockwise).
legal_rotate(57,black,1,counterclockwise).
legal_rotate(57,black,3,clockwise).
legal_rotate(57,black,2,counterclockwise).
legal_rotate(57,black,1,clockwise).
legal_rotate(57,black,3,counterclockwise).
legal_rotate(57,black,4,clockwise).
legal_rotate(57,black,2,clockwise).
legal_rotate(59,red,2,clockwise).
legal_rotate(59,red,3,counterclockwise).
legal_rotate(59,red,4,clockwise).
legal_rotate(59,red,2,counterclockwise).
legal_rotate(59,red,4,counterclockwise).
legal_rotate(59,red,1,counterclockwise).
legal_rotate(59,red,3,clockwise).
legal_rotate(59,red,1,clockwise).
legal_rotate(61,black,4,counterclockwise).
legal_rotate(61,black,1,counterclockwise).
legal_rotate(61,black,3,clockwise).
legal_rotate(61,black,2,counterclockwise).
legal_rotate(61,black,1,clockwise).
legal_rotate(61,black,3,counterclockwise).
legal_rotate(61,black,4,clockwise).
legal_rotate(61,black,2,clockwise).
