legal(1,black,defect).
legal(1,black,cooperate).
legal(1,white,defect).
legal(1,white,cooperate).
legal(2,black,defect).
legal(2,black,cooperate).
legal(2,white,defect).
legal(2,white,cooperate).
legal(3,black,defect).
legal(3,black,cooperate).
legal(3,white,defect).
legal(3,white,cooperate).
legal(4,black,defect).
legal(4,black,cooperate).
legal(4,white,defect).
legal(4,white,cooperate).
legal(5,black,defect).
legal(5,black,cooperate).
legal(5,white,defect).
legal(5,white,cooperate).
legal(6,black,defect).
legal(6,black,cooperate).
legal(6,white,defect).
legal(6,white,cooperate).
legal(7,black,defect).
legal(7,black,cooperate).
legal(7,white,defect).
legal(7,white,cooperate).
legal(8,black,defect).
legal(8,black,cooperate).
legal(8,white,defect).
legal(8,white,cooperate).
legal(9,black,defect).
legal(9,black,cooperate).
legal(9,white,defect).
legal(9,white,cooperate).
legal(10,black,defect).
legal(10,black,cooperate).
legal(10,white,defect).
legal(10,white,cooperate).
legal(11,black,defect).
legal(11,black,cooperate).
legal(11,white,defect).
legal(11,white,cooperate).
legal(12,black,defect).
legal(12,black,cooperate).
legal(12,white,defect).
legal(12,white,cooperate).
legal(13,black,defect).
legal(13,black,cooperate).
legal(13,white,defect).
legal(13,white,cooperate).
legal(14,black,defect).
legal(14,black,cooperate).
legal(14,white,defect).
legal(14,white,cooperate).
legal(15,black,defect).
legal(15,black,cooperate).
legal(15,white,defect).
legal(15,white,cooperate).
legal(16,black,defect).
legal(16,black,cooperate).
legal(16,white,defect).
legal(16,white,cooperate).
legal(17,black,defect).
legal(17,black,cooperate).
legal(17,white,defect).
legal(17,white,cooperate).
legal(18,black,defect).
legal(18,black,cooperate).
legal(18,white,defect).
legal(18,white,cooperate).
legal(19,black,defect).
legal(19,black,cooperate).
legal(19,white,defect).
legal(19,white,cooperate).
legal(20,black,defect).
legal(20,black,cooperate).
legal(20,white,defect).
legal(20,white,cooperate).
legal(21,black,defect).
legal(21,black,cooperate).
legal(21,white,defect).
legal(21,white,cooperate).
legal(22,black,defect).
legal(22,black,cooperate).
legal(22,white,defect).
legal(22,white,cooperate).
legal(23,black,defect).
legal(23,black,cooperate).
legal(23,white,defect).
legal(23,white,cooperate).
legal(24,black,defect).
legal(24,black,cooperate).
legal(24,white,defect).
legal(24,white,cooperate).
legal(25,black,defect).
legal(25,black,cooperate).
legal(25,white,defect).
legal(25,white,cooperate).
legal(26,black,defect).
legal(26,black,cooperate).
legal(26,white,defect).
legal(26,white,cooperate).
legal(27,black,defect).
legal(27,black,cooperate).
legal(27,white,defect).
legal(27,white,cooperate).
legal(28,black,defect).
legal(28,black,cooperate).
legal(28,white,defect).
legal(28,white,cooperate).
legal(29,black,defect).
legal(29,black,cooperate).
legal(29,white,defect).
legal(29,white,cooperate).
legal(30,black,defect).
legal(30,black,cooperate).
legal(30,white,defect).
legal(30,white,cooperate).
legal(31,black,defect).
legal(31,black,cooperate).
legal(31,white,defect).
legal(31,white,cooperate).
legal(32,black,defect).
legal(32,black,cooperate).
legal(32,white,defect).
legal(32,white,cooperate).
legal(33,black,defect).
legal(33,black,cooperate).
legal(33,white,defect).
legal(33,white,cooperate).
legal(34,black,defect).
legal(34,black,cooperate).
legal(34,white,defect).
legal(34,white,cooperate).
legal(35,black,defect).
legal(35,black,cooperate).
legal(35,white,defect).
legal(35,white,cooperate).
legal(36,black,defect).
legal(36,black,cooperate).
legal(36,white,defect).
legal(36,white,cooperate).
legal(37,black,defect).
legal(37,black,cooperate).
legal(37,white,defect).
legal(37,white,cooperate).
legal(38,black,defect).
legal(38,black,cooperate).
legal(38,white,defect).
legal(38,white,cooperate).
legal(39,black,defect).
legal(39,black,cooperate).
legal(39,white,defect).
legal(39,white,cooperate).
legal(40,black,defect).
legal(40,black,cooperate).
legal(40,white,defect).
legal(40,white,cooperate).
legal(41,black,defect).
legal(41,black,cooperate).
legal(41,white,defect).
legal(41,white,cooperate).
legal(42,black,defect).
legal(42,black,cooperate).
legal(42,white,defect).
legal(42,white,cooperate).
legal(43,black,defect).
legal(43,black,cooperate).
legal(43,white,defect).
legal(43,white,cooperate).
legal(44,black,defect).
legal(44,black,cooperate).
legal(44,white,defect).
legal(44,white,cooperate).
legal(45,black,defect).
legal(45,black,cooperate).
legal(45,white,defect).
legal(45,white,cooperate).
legal(46,black,defect).
legal(46,black,cooperate).
legal(46,white,defect).
legal(46,white,cooperate).
legal(47,black,defect).
legal(47,black,cooperate).
legal(47,white,defect).
legal(47,white,cooperate).
legal(48,black,defect).
legal(48,black,cooperate).
legal(48,white,defect).
legal(48,white,cooperate).
legal(49,black,defect).
legal(49,black,cooperate).
legal(49,white,defect).
legal(49,white,cooperate).
legal(50,black,defect).
legal(50,black,cooperate).
legal(50,white,defect).
legal(50,white,cooperate).
legal(51,black,defect).
legal(51,black,cooperate).
legal(51,white,defect).
legal(51,white,cooperate).
legal(52,black,defect).
legal(52,black,cooperate).
legal(52,white,defect).
legal(52,white,cooperate).
legal(53,black,defect).
legal(53,black,cooperate).
legal(53,white,defect).
legal(53,white,cooperate).
legal(54,black,defect).
legal(54,black,cooperate).
legal(54,white,defect).
legal(54,white,cooperate).
legal(55,black,defect).
legal(55,black,cooperate).
legal(55,white,defect).
legal(55,white,cooperate).
legal(56,black,defect).
legal(56,black,cooperate).
legal(56,white,defect).
legal(56,white,cooperate).
legal(57,black,defect).
legal(57,black,cooperate).
legal(57,white,defect).
legal(57,white,cooperate).
legal(58,black,defect).
legal(58,black,cooperate).
legal(58,white,defect).
legal(58,white,cooperate).
legal(59,black,defect).
legal(59,black,cooperate).
legal(59,white,defect).
legal(59,white,cooperate).
legal(60,black,defect).
legal(60,black,cooperate).
legal(60,white,defect).
legal(60,white,cooperate).
legal(61,black,defect).
legal(61,black,cooperate).
legal(61,white,defect).
legal(61,white,cooperate).
legal(62,black,defect).
legal(62,black,cooperate).
legal(62,white,defect).
legal(62,white,cooperate).
legal(63,black,defect).
legal(63,black,cooperate).
legal(63,white,defect).
legal(63,white,cooperate).
legal(64,black,defect).
legal(64,black,cooperate).
legal(64,white,defect).
legal(64,white,cooperate).
legal(65,black,defect).
legal(65,black,cooperate).
legal(65,white,defect).
legal(65,white,cooperate).
legal(66,black,defect).
legal(66,black,cooperate).
legal(66,white,defect).
legal(66,white,cooperate).
legal(67,black,defect).
legal(67,black,cooperate).
legal(67,white,defect).
legal(67,white,cooperate).
legal(68,black,defect).
legal(68,black,cooperate).
legal(68,white,defect).
legal(68,white,cooperate).
legal(69,black,defect).
legal(69,black,cooperate).
legal(69,white,defect).
legal(69,white,cooperate).
legal(70,black,defect).
legal(70,black,cooperate).
legal(70,white,defect).
legal(70,white,cooperate).
legal(71,black,defect).
legal(71,black,cooperate).
legal(71,white,defect).
legal(71,white,cooperate).
legal(72,black,defect).
legal(72,black,cooperate).
legal(72,white,defect).
legal(72,white,cooperate).
legal(73,black,defect).
legal(73,black,cooperate).
legal(73,white,defect).
legal(73,white,cooperate).
legal(74,black,defect).
legal(74,black,cooperate).
legal(74,white,defect).
legal(74,white,cooperate).
legal(75,black,defect).
legal(75,black,cooperate).
legal(75,white,defect).
legal(75,white,cooperate).
legal(76,black,defect).
legal(76,black,cooperate).
legal(76,white,defect).
legal(76,white,cooperate).
legal(77,black,defect).
legal(77,black,cooperate).
legal(77,white,defect).
legal(77,white,cooperate).
legal(78,black,defect).
legal(78,black,cooperate).
legal(78,white,defect).
legal(78,white,cooperate).
legal(79,black,defect).
legal(79,black,cooperate).
legal(79,white,defect).
legal(79,white,cooperate).
legal(80,black,defect).
legal(80,black,cooperate).
legal(80,white,defect).
legal(80,white,cooperate).
legal(81,black,defect).
legal(81,black,cooperate).
legal(81,white,defect).
legal(81,white,cooperate).
legal(82,black,defect).
legal(82,black,cooperate).
legal(82,white,defect).
legal(82,white,cooperate).
legal(83,black,defect).
legal(83,black,cooperate).
legal(83,white,defect).
legal(83,white,cooperate).
legal(84,black,defect).
legal(84,black,cooperate).
legal(84,white,defect).
legal(84,white,cooperate).
legal(85,black,defect).
legal(85,black,cooperate).
legal(85,white,defect).
legal(85,white,cooperate).
legal(86,black,defect).
legal(86,black,cooperate).
legal(86,white,defect).
legal(86,white,cooperate).
legal(87,black,defect).
legal(87,black,cooperate).
legal(87,white,defect).
legal(87,white,cooperate).
legal(88,black,defect).
legal(88,black,cooperate).
legal(88,white,defect).
legal(88,white,cooperate).
legal(89,black,defect).
legal(89,black,cooperate).
legal(89,white,defect).
legal(89,white,cooperate).
legal(90,black,defect).
legal(90,black,cooperate).
legal(90,white,defect).
legal(90,white,cooperate).
legal(91,black,defect).
legal(91,black,cooperate).
legal(91,white,defect).
legal(91,white,cooperate).
legal(92,black,defect).
legal(92,black,cooperate).
legal(92,white,defect).
legal(92,white,cooperate).
legal(93,black,defect).
legal(93,black,cooperate).
legal(93,white,defect).
legal(93,white,cooperate).
legal(94,black,defect).
legal(94,black,cooperate).
legal(94,white,defect).
legal(94,white,cooperate).
legal(95,black,defect).
legal(95,black,cooperate).
legal(95,white,defect).
legal(95,white,cooperate).
legal(96,black,defect).
legal(96,black,cooperate).
legal(96,white,defect).
legal(96,white,cooperate).
legal(97,black,defect).
legal(97,black,cooperate).
legal(97,white,defect).
legal(97,white,cooperate).
legal(98,black,defect).
legal(98,black,cooperate).
legal(98,white,defect).
legal(98,white,cooperate).
legal(99,black,defect).
legal(99,black,cooperate).
legal(99,white,defect).
legal(99,white,cooperate).
legal(100,black,defect).
legal(100,black,cooperate).
legal(100,white,defect).
legal(100,white,cooperate).
legal(101,black,defect).
legal(101,black,cooperate).
legal(101,white,defect).
legal(101,white,cooperate).
legal(102,black,defect).
legal(102,black,cooperate).
legal(102,white,defect).
legal(102,white,cooperate).
legal(103,black,defect).
legal(103,black,cooperate).
legal(103,white,defect).
legal(103,white,cooperate).
legal(104,black,defect).
legal(104,black,cooperate).
legal(104,white,defect).
legal(104,white,cooperate).
legal(105,black,defect).
legal(105,black,cooperate).
legal(105,white,defect).
legal(105,white,cooperate).
legal(106,black,defect).
legal(106,black,cooperate).
legal(106,white,defect).
legal(106,white,cooperate).
legal(107,black,defect).
legal(107,black,cooperate).
legal(107,white,defect).
legal(107,white,cooperate).
legal(108,black,defect).
legal(108,black,cooperate).
legal(108,white,defect).
legal(108,white,cooperate).
legal(109,black,defect).
legal(109,black,cooperate).
legal(109,white,defect).
legal(109,white,cooperate).
legal(110,black,defect).
legal(110,black,cooperate).
legal(110,white,defect).
legal(110,white,cooperate).
legal(111,black,defect).
legal(111,black,cooperate).
legal(111,white,defect).
legal(111,white,cooperate).
legal(112,black,defect).
legal(112,black,cooperate).
legal(112,white,defect).
legal(112,white,cooperate).
legal(113,black,defect).
legal(113,black,cooperate).
legal(113,white,defect).
legal(113,white,cooperate).
legal(114,black,defect).
legal(114,black,cooperate).
legal(114,white,defect).
legal(114,white,cooperate).
legal(115,black,defect).
legal(115,black,cooperate).
legal(115,white,defect).
legal(115,white,cooperate).
legal(116,black,defect).
legal(116,black,cooperate).
legal(116,white,defect).
legal(116,white,cooperate).
legal(117,black,defect).
legal(117,black,cooperate).
legal(117,white,defect).
legal(117,white,cooperate).
legal(118,black,defect).
legal(118,black,cooperate).
legal(118,white,defect).
legal(118,white,cooperate).
legal(119,black,defect).
legal(119,black,cooperate).
legal(119,white,defect).
legal(119,white,cooperate).
legal(120,black,defect).
legal(120,black,cooperate).
legal(120,white,defect).
legal(120,white,cooperate).
legal(121,black,defect).
legal(121,black,cooperate).
legal(121,white,defect).
legal(121,white,cooperate).
legal(122,black,defect).
legal(122,black,cooperate).
legal(122,white,defect).
legal(122,white,cooperate).
legal(123,black,defect).
legal(123,black,cooperate).
legal(123,white,defect).
legal(123,white,cooperate).
legal(124,black,defect).
legal(124,black,cooperate).
legal(124,white,defect).
legal(124,white,cooperate).
legal(125,black,defect).
legal(125,black,cooperate).
legal(125,white,defect).
legal(125,white,cooperate).
legal(126,black,defect).
legal(126,black,cooperate).
legal(126,white,defect).
legal(126,white,cooperate).
legal(127,black,defect).
legal(127,black,cooperate).
legal(127,white,defect).
legal(127,white,cooperate).
legal(128,black,defect).
legal(128,black,cooperate).
legal(128,white,defect).
legal(128,white,cooperate).
legal(129,black,defect).
legal(129,black,cooperate).
legal(129,white,defect).
legal(129,white,cooperate).
legal(130,black,defect).
legal(130,black,cooperate).
legal(130,white,defect).
legal(130,white,cooperate).
legal(131,black,defect).
legal(131,black,cooperate).
legal(131,white,defect).
legal(131,white,cooperate).
legal(132,black,defect).
legal(132,black,cooperate).
legal(132,white,defect).
legal(132,white,cooperate).
legal(133,black,defect).
legal(133,black,cooperate).
legal(133,white,defect).
legal(133,white,cooperate).
legal(134,black,defect).
legal(134,black,cooperate).
legal(134,white,defect).
legal(134,white,cooperate).
legal(135,black,defect).
legal(135,black,cooperate).
legal(135,white,defect).
legal(135,white,cooperate).
legal(136,black,defect).
legal(136,black,cooperate).
legal(136,white,defect).
legal(136,white,cooperate).
legal(137,black,defect).
legal(137,black,cooperate).
legal(137,white,defect).
legal(137,white,cooperate).
legal(138,black,defect).
legal(138,black,cooperate).
legal(138,white,defect).
legal(138,white,cooperate).
legal(139,black,defect).
legal(139,black,cooperate).
legal(139,white,defect).
legal(139,white,cooperate).
legal(140,black,defect).
legal(140,black,cooperate).
legal(140,white,defect).
legal(140,white,cooperate).
legal(141,black,defect).
legal(141,black,cooperate).
legal(141,white,defect).
legal(141,white,cooperate).
legal(142,black,defect).
legal(142,black,cooperate).
legal(142,white,defect).
legal(142,white,cooperate).
legal(143,black,defect).
legal(143,black,cooperate).
legal(143,white,defect).
legal(143,white,cooperate).
legal(144,black,defect).
legal(144,black,cooperate).
legal(144,white,defect).
legal(144,white,cooperate).
legal(145,black,defect).
legal(145,black,cooperate).
legal(145,white,defect).
legal(145,white,cooperate).
legal(146,black,defect).
legal(146,black,cooperate).
legal(146,white,defect).
legal(146,white,cooperate).
legal(147,black,defect).
legal(147,black,cooperate).
legal(147,white,defect).
legal(147,white,cooperate).
legal(148,black,defect).
legal(148,black,cooperate).
legal(148,white,defect).
legal(148,white,cooperate).
legal(149,black,defect).
legal(149,black,cooperate).
legal(149,white,defect).
legal(149,white,cooperate).
legal(150,black,defect).
legal(150,black,cooperate).
legal(150,white,defect).
legal(150,white,cooperate).
legal(151,black,defect).
legal(151,black,cooperate).
legal(151,white,defect).
legal(151,white,cooperate).
legal(152,black,defect).
legal(152,black,cooperate).
legal(152,white,defect).
legal(152,white,cooperate).
legal(153,black,defect).
legal(153,black,cooperate).
legal(153,white,defect).
legal(153,white,cooperate).
legal(154,black,defect).
legal(154,black,cooperate).
legal(154,white,defect).
legal(154,white,cooperate).
legal(155,black,defect).
legal(155,black,cooperate).
legal(155,white,defect).
legal(155,white,cooperate).
legal(156,black,defect).
legal(156,black,cooperate).
legal(156,white,defect).
legal(156,white,cooperate).
legal(157,black,defect).
legal(157,black,cooperate).
legal(157,white,defect).
legal(157,white,cooperate).
legal(158,black,defect).
legal(158,black,cooperate).
legal(158,white,defect).
legal(158,white,cooperate).
legal(159,black,defect).
legal(159,black,cooperate).
legal(159,white,defect).
legal(159,white,cooperate).
legal(160,black,defect).
legal(160,black,cooperate).
legal(160,white,defect).
legal(160,white,cooperate).
legal(161,black,defect).
legal(161,black,cooperate).
legal(161,white,defect).
legal(161,white,cooperate).
legal(162,black,defect).
legal(162,black,cooperate).
legal(162,white,defect).
legal(162,white,cooperate).
legal(163,black,defect).
legal(163,black,cooperate).
legal(163,white,defect).
legal(163,white,cooperate).
legal(164,black,defect).
legal(164,black,cooperate).
legal(164,white,defect).
legal(164,white,cooperate).
legal(165,black,defect).
legal(165,black,cooperate).
legal(165,white,defect).
legal(165,white,cooperate).
legal(166,black,defect).
legal(166,black,cooperate).
legal(166,white,defect).
legal(166,white,cooperate).
legal(167,black,defect).
legal(167,black,cooperate).
legal(167,white,defect).
legal(167,white,cooperate).
legal(168,black,defect).
legal(168,black,cooperate).
legal(168,white,defect).
legal(168,white,cooperate).
