legal(1,black,right).
legal(1,black,fire).
legal(1,black,noop).
legal(2,black,right).
legal(2,black,fire).
legal(2,black,noop).
legal(3,black,right).
legal(3,black,fire).
legal(3,black,noop).
legal(4,black,right).
legal(4,black,noop).
legal(5,black,right).
legal(5,black,left).
legal(5,black,noop).
legal(6,black,right).
legal(6,black,left).
legal(6,black,noop).
legal(7,black,right).
legal(7,black,left).
legal(7,black,noop).
legal(8,black,right).
legal(8,black,left).
legal(8,black,noop).
legal(9,black,right).
legal(9,black,left).
legal(9,black,noop).
legal(10,black,right).
legal(10,black,fire).
legal(10,black,noop).
legal(11,black,right).
legal(11,black,fire).
legal(11,black,noop).
legal(12,black,right).
legal(12,black,fire).
legal(12,black,noop).
legal(13,black,right).
legal(13,black,noop).
legal(14,black,right).
legal(14,black,left).
legal(14,black,noop).
legal(15,black,right).
legal(15,black,left).
legal(15,black,noop).
legal(16,black,right).
legal(16,black,left).
legal(16,black,noop).
legal(17,black,right).
legal(17,black,left).
legal(17,black,noop).
legal(18,black,right).
legal(18,black,left).
legal(18,black,noop).
legal(19,black,right).
legal(19,black,fire).
legal(19,black,noop).
legal(20,black,right).
legal(20,black,fire).
legal(20,black,noop).
legal(21,black,right).
legal(21,black,fire).
legal(21,black,noop).
legal(22,black,right).
legal(22,black,noop).
legal(23,black,right).
legal(23,black,noop).
legal(24,black,right).
legal(24,black,left).
legal(24,black,noop).
legal(25,black,right).
legal(25,black,left).
legal(25,black,noop).
legal(26,black,right).
legal(26,black,left).
legal(26,black,noop).
legal(27,black,right).
legal(27,black,noop).
legal(28,black,right).
legal(28,black,fire).
legal(28,black,noop).
legal(29,black,right).
legal(29,black,fire).
legal(29,black,noop).
legal(30,black,right).
legal(30,black,fire).
legal(30,black,noop).
legal(31,black,right).
legal(31,black,noop).
legal(32,black,right).
legal(32,black,left).
legal(32,black,noop).
legal(33,black,right).
legal(33,black,left).
legal(33,black,noop).
legal(34,black,right).
legal(34,black,left).
legal(34,black,noop).
legal(35,black,right).
legal(35,black,left).
legal(35,black,noop).
legal(36,black,right).
legal(36,black,left).
legal(36,black,noop).
legal(37,black,right).
legal(37,black,fire).
legal(37,black,noop).
legal(38,black,right).
legal(38,black,fire).
legal(38,black,noop).
legal(39,black,right).
legal(39,black,fire).
legal(39,black,noop).
legal(40,black,right).
legal(40,black,noop).
legal(41,black,right).
legal(41,black,left).
legal(41,black,noop).
legal(42,black,right).
legal(42,black,noop).
legal(43,black,right).
legal(43,black,left).
legal(43,black,noop).
legal(44,black,right).
legal(44,black,noop).
legal(45,black,right).
legal(45,black,left).
legal(45,black,noop).
legal(46,black,right).
legal(46,black,fire).
legal(46,black,noop).
legal(47,black,right).
legal(47,black,fire).
legal(47,black,noop).
legal(48,black,right).
legal(48,black,fire).
legal(48,black,noop).
legal(49,black,right).
legal(49,black,noop).
legal(50,black,right).
legal(50,black,left).
legal(50,black,noop).
legal(51,black,right).
legal(51,black,left).
legal(51,black,noop).
legal(52,black,right).
legal(52,black,noop).
legal(53,black,right).
legal(53,black,left).
legal(53,black,noop).
legal(54,black,right).
legal(54,black,left).
legal(54,black,noop).
legal(55,black,right).
legal(55,black,fire).
legal(55,black,noop).
legal(56,black,right).
legal(56,black,fire).
legal(56,black,noop).
legal(57,black,right).
legal(57,black,fire).
legal(57,black,noop).
legal(58,black,right).
legal(58,black,noop).
legal(59,black,right).
legal(59,black,noop).
legal(60,black,right).
legal(60,black,noop).
legal(61,black,right).
legal(61,black,left).
legal(61,black,noop).
legal(62,black,right).
legal(62,black,noop).
legal(63,black,right).
legal(63,black,left).
legal(63,black,noop).
legal(64,black,right).
legal(64,black,fire).
legal(64,black,noop).
legal(65,black,right).
legal(65,black,fire).
legal(65,black,noop).
legal(66,black,right).
legal(66,black,fire).
legal(66,black,noop).
legal(67,black,right).
legal(67,black,noop).
legal(68,black,right).
legal(68,black,left).
legal(68,black,noop).
legal(69,black,right).
legal(69,black,left).
legal(69,black,noop).
legal(70,black,right).
legal(70,black,noop).
legal(71,black,right).
legal(71,black,left).
legal(71,black,noop).
legal(72,black,right).
legal(72,black,left).
legal(72,black,noop).
