legal_a(1,robot,1).
legal_a(1,robot,7).
legal_a(1,robot,5).
legal_a(1,robot,9).
legal_a(1,robot,4).
legal_a(1,robot,3).
legal_a(1,robot,6).
legal_a(1,robot,2).
legal_a(1,robot,8).
legal_a(2,robot,1).
legal_a(2,robot,7).
legal_a(2,robot,5).
legal_a(2,robot,9).
legal_a(2,robot,4).
legal_a(2,robot,3).
legal_a(2,robot,6).
legal_a(2,robot,2).
legal_a(2,robot,8).
legal_a(3,robot,1).
legal_a(3,robot,7).
legal_a(3,robot,5).
legal_a(3,robot,9).
legal_a(3,robot,4).
legal_a(3,robot,3).
legal_a(3,robot,6).
legal_a(3,robot,2).
legal_a(3,robot,8).
legal_a(4,robot,1).
legal_a(4,robot,7).
legal_a(4,robot,5).
legal_a(4,robot,9).
legal_a(4,robot,4).
legal_a(4,robot,3).
legal_a(4,robot,6).
legal_a(4,robot,2).
legal_a(4,robot,8).
legal_a(5,robot,1).
legal_a(5,robot,7).
legal_a(5,robot,5).
legal_a(5,robot,9).
legal_a(5,robot,4).
legal_a(5,robot,3).
legal_a(5,robot,6).
legal_a(5,robot,2).
legal_a(5,robot,8).
legal_a(6,robot,1).
legal_a(6,robot,7).
legal_a(6,robot,5).
legal_a(6,robot,9).
legal_a(6,robot,4).
legal_a(6,robot,3).
legal_a(6,robot,6).
legal_a(6,robot,2).
legal_a(6,robot,8).
legal_a(7,robot,1).
legal_a(7,robot,7).
legal_a(7,robot,5).
legal_a(7,robot,9).
legal_a(7,robot,4).
legal_a(7,robot,3).
legal_a(7,robot,6).
legal_a(7,robot,2).
legal_a(7,robot,8).
