legal(1,black,noop).
legal_move(1,red,a,c).
legal_move(1,red,d,c).
legal(2,black,noop).
legal_move(2,red,a,c).
legal_move(2,red,d,c).
legal(3,red,noop).
legal_move(3,black,e,d).
legal(4,black,noop).
legal_move(4,red,c,e).
legal_move(5,black,b,c).
legal(5,red,noop).
legal_move(5,black,d,c).
legal(6,black,noop).
legal_move(6,red,e,d).
legal_move(7,black,b,e).
legal(7,red,noop).
legal_move(7,black,c,e).
legal(8,black,noop).
legal_move(8,red,a,b).
legal(9,red,noop).
legal_move(9,black,c,a).
legal(10,black,noop).
legal_move(10,red,b,c).
legal_move(10,red,d,c).
legal(11,red,noop).
legal_move(11,black,e,d).
legal(12,black,noop).
legal_move(12,red,b,e).
legal_move(12,red,c,e).
legal_move(13,black,a,c).
legal(13,red,noop).
legal_move(13,black,d,c).
legal(14,black,noop).
legal_move(14,red,e,d).
legal(15,red,noop).
legal_move(15,black,c,e).
legal(16,black,noop).
legal_move(16,red,b,c).
legal_move(16,red,d,c).
legal(17,red,noop).
legal_move(17,black,e,d).
legal(18,black,noop).
legal_move(18,red,b,e).
legal_move(18,red,c,e).
legal(19,red,noop).
legal_move(19,black,a,b).
legal(20,black,noop).
legal_move(20,red,c,a).
legal(21,black,noop).
legal_move(21,red,a,c).
legal_move(21,red,d,c).
legal(22,black,noop).
legal_move(22,red,a,c).
legal_move(22,red,d,c).
legal(23,red,noop).
legal_move(23,black,b,a).
legal(24,black,noop).
legal_move(24,red,c,b).
legal_move(25,black,a,c).
legal(25,red,noop).
legal_move(25,black,e,c).
legal(26,black,noop).
legal_move(26,red,b,e).
legal_move(26,red,d,e).
legal(27,red,noop).
legal_move(27,black,c,d).
legal(28,black,noop).
legal_move(28,red,e,c).
legal_move(28,red,b,c).
legal(29,red,noop).
legal_move(29,black,a,b).
legal(30,black,noop).
legal_move(30,red,c,a).
legal_move(31,black,b,c).
legal(31,red,noop).
legal_move(31,black,d,c).
legal(32,black,noop).
legal_move(32,red,e,d).
legal_move(33,black,b,e).
legal(33,red,noop).
legal_move(33,black,c,e).
legal(34,black,noop).
legal_move(34,red,a,c).
legal_move(34,red,d,c).
legal(35,red,noop).
legal_move(35,black,b,a).
legal(36,black,noop).
legal_move(36,red,c,b).
legal_move(37,black,a,c).
legal(37,red,noop).
legal_move(37,black,e,c).
legal(38,black,noop).
legal_move(38,red,b,a).
legal_move(39,black,e,b).
legal(39,red,noop).
legal_move(39,black,c,b).
legal(40,black,noop).
legal_move(40,red,d,e).
legal(41,black,noop).
legal_move(41,red,d,c).
legal_move(41,red,a,c).
legal(42,black,noop).
legal_move(42,red,d,c).
legal_move(42,red,a,c).
legal(43,red,noop).
legal_move(43,black,e,d).
legal(44,black,noop).
legal_move(44,red,c,e).
legal_move(45,black,b,c).
legal(45,red,noop).
legal_move(45,black,d,c).
legal(46,black,noop).
legal_move(46,red,e,b).
legal_move(46,red,a,b).
legal(47,red,noop).
legal_move(47,black,d,e).
legal_move(47,black,c,e).
legal(48,black,noop).
legal_move(48,red,a,c).
legal_move(48,red,d,c).
legal(49,black,noop).
legal_move(49,red,a,c).
legal_move(49,red,d,c).
legal(50,red,noop).
legal_move(50,black,b,a).
legal(51,black,noop).
legal_move(51,red,c,b).
legal_move(52,black,a,c).
legal(52,red,noop).
legal_move(52,black,e,c).
legal(53,black,noop).
legal_move(53,red,b,e).
legal_move(53,red,d,e).
legal(54,red,noop).
legal_move(54,black,a,b).
legal_move(54,black,c,b).
legal(55,black,noop).
legal_move(55,red,d,c).
legal_move(55,red,a,c).
legal(56,black,noop).
legal_move(56,red,d,c).
legal_move(56,red,a,c).
legal(57,red,noop).
legal_move(57,black,e,d).
legal(58,black,noop).
legal_move(58,red,c,e).
legal_move(59,black,b,c).
legal(59,red,noop).
legal_move(59,black,d,c).
legal(60,black,noop).
legal_move(60,red,e,b).
legal_move(60,red,a,b).
legal(61,red,noop).
legal_move(61,black,c,a).
legal(62,black,noop).
legal_move(62,red,e,c).
legal_move(62,red,b,c).
legal(63,red,noop).
legal_move(63,black,d,e).
legal(64,black,noop).
legal_move(64,red,c,d).
legal_move(65,black,a,c).
legal(65,red,noop).
legal_move(65,black,e,c).
legal(66,black,noop).
legal_move(66,red,b,e).
legal_move(66,red,d,e).
legal(67,red,noop).
legal_move(67,black,c,d).
legal(68,black,noop).
legal_move(68,red,e,c).
legal_move(68,red,b,c).
legal(69,red,noop).
legal_move(69,black,d,e).
legal(70,black,noop).
legal_move(70,red,c,d).
legal_move(71,black,a,c).
legal(71,red,noop).
legal_move(71,black,e,c).
legal(72,black,noop).
legal_move(72,red,b,e).
legal_move(72,red,d,e).
legal(73,red,noop).
legal_move(73,black,c,d).
legal(74,black,noop).
legal_move(74,red,e,c).
legal_move(74,red,b,c).
legal(75,black,noop).
legal_move(75,red,d,c).
legal_move(75,red,a,c).
legal(76,black,noop).
legal_move(76,red,d,c).
legal_move(76,red,a,c).
legal(77,red,noop).
legal_move(77,black,e,d).
legal(78,black,noop).
legal_move(78,red,c,e).
legal_move(79,black,b,c).
legal(79,red,noop).
legal_move(79,black,d,c).
legal(80,black,noop).
legal_move(80,red,e,b).
legal_move(80,red,a,b).
legal(81,red,noop).
legal_move(81,black,c,a).
legal(82,black,noop).
legal_move(82,red,e,c).
legal_move(82,red,b,c).
legal(83,red,noop).
legal_move(83,black,a,b).
legal(84,black,noop).
legal_move(84,red,c,a).
legal_move(85,black,b,c).
legal(85,red,noop).
legal_move(85,black,d,c).
legal(86,black,noop).
legal_move(86,red,e,b).
legal_move(86,red,a,b).
legal(87,red,noop).
legal_move(87,black,c,a).
legal(88,black,noop).
legal_move(88,red,e,c).
legal_move(88,red,b,c).
legal(89,red,noop).
legal_move(89,black,d,e).
legal(90,black,noop).
legal_move(90,red,c,d).
legal_move(91,black,a,c).
legal(91,red,noop).
legal_move(91,black,e,c).
legal(92,black,noop).
legal_move(92,red,b,e).
legal_move(92,red,d,e).
legal(93,red,noop).
legal_move(93,black,c,d).
legal(94,black,noop).
legal_move(94,red,e,c).
legal_move(94,red,b,c).
legal(95,black,noop).
legal_move(95,red,a,c).
legal_move(95,red,d,c).
legal(96,black,noop).
legal_move(96,red,a,c).
legal_move(96,red,d,c).
legal(97,red,noop).
legal_move(97,black,e,d).
legal(98,black,noop).
legal_move(98,red,c,e).
legal_move(99,black,b,c).
legal(99,red,noop).
legal_move(99,black,d,c).
legal(100,black,noop).
legal_move(100,red,e,b).
legal_move(100,red,a,b).
legal(101,red,noop).
legal_move(101,black,c,a).
legal(102,black,noop).
legal_move(102,red,e,c).
legal_move(102,red,b,c).
legal(103,red,noop).
legal_move(103,black,d,e).
legal(104,black,noop).
legal_move(104,red,c,d).
legal_move(105,black,a,c).
legal(105,red,noop).
legal_move(105,black,e,c).
legal(106,black,noop).
legal_move(106,red,b,e).
legal_move(106,red,d,e).
legal(107,red,noop).
legal_move(107,black,c,d).
legal(108,black,noop).
legal_move(108,red,e,c).
legal_move(108,red,b,c).
legal(109,red,noop).
legal_move(109,black,d,e).
legal(110,black,noop).
legal_move(110,red,c,d).
legal_move(111,black,a,c).
legal(111,red,noop).
legal_move(111,black,e,c).
legal(112,black,noop).
legal_move(112,red,b,a).
legal_move(113,black,e,b).
legal(113,red,noop).
legal_move(113,black,c,b).
legal(114,black,noop).
legal_move(114,red,d,e).
legal(115,black,noop).
legal_move(115,red,a,c).
legal_move(115,red,d,c).
legal(116,black,noop).
legal_move(116,red,a,c).
legal_move(116,red,d,c).
legal(117,red,noop).
legal_move(117,black,b,a).
legal(118,black,noop).
legal_move(118,red,c,b).
legal_move(119,black,a,c).
legal(119,red,noop).
legal_move(119,black,e,c).
legal(120,black,noop).
legal_move(120,red,b,e).
legal_move(120,red,d,e).
legal(121,red,noop).
legal_move(121,black,c,d).
legal(122,black,noop).
legal_move(122,red,e,c).
legal_move(122,red,b,c).
legal(123,red,noop).
legal_move(123,black,d,e).
legal(124,black,noop).
legal_move(124,red,c,d).
legal_move(125,black,a,c).
legal(125,red,noop).
legal_move(125,black,e,c).
legal(126,black,noop).
legal_move(126,red,b,e).
legal_move(126,red,d,e).
legal(127,red,noop).
legal_move(127,black,c,d).
legal(128,black,noop).
legal_move(128,red,e,c).
legal_move(128,red,b,c).
legal(129,red,noop).
legal_move(129,black,d,e).
legal(130,black,noop).
legal_move(130,red,c,d).
legal_move(131,black,a,c).
legal(131,red,noop).
legal_move(131,black,e,c).
legal(132,black,noop).
legal_move(132,red,b,a).
legal_move(133,black,e,b).
legal(133,red,noop).
legal_move(133,black,c,b).
legal(134,black,noop).
legal_move(134,red,d,e).
