next_control(1,black).
next_control(2,black).
next_control(3,white).
next_control(4,black).
next_control(5,white).
next_control(6,black).
next_control(7,white).
next_control(8,black).
next_control(9,black).
next_control(10,black).
next_control(11,white).
next_control(12,black).
next_control(13,black).
next_control(14,black).
next_control(15,black).
next_control(16,white).
next_control(17,black).
next_control(18,black).
next_control(19,white).
next_control(20,black).
next_control(21,black).
next_control(22,white).
next_control(23,black).
next_control(24,white).
next_control(25,black).
next_control(26,black).
next_control(27,white).
next_control(569,black).
next_control(570,black).
next_control(571,black).
next_control(572,black).
next_control(573,black).
next_control(574,black).
next_control(575,black).
next_control(576,black).
next_control(577,black).
next_control(578,black).
next_control(579,black).
next_control(580,black).
next_control(581,black).
next_control(582,black).
next_control(583,black).
